import { config } from "@/config";
import { db,stateGet } from "@/features/db/client";
import { categorizationSummary } from "@/features/categorization/query";

function count(sql:string):number{return(db().prepare(sql).get() as{count:number}).count}
function rows(sql:string):Array<Record<string,unknown>>{return db().prepare(sql).all() as Array<Record<string,unknown>>}
function jsonState(key:string):Record<string,unknown>{try{return JSON.parse(stateGet(key,"{}")) as Record<string,unknown>}catch{return{}}}
function present(column:string,path:string):string{return`((json_type(${column},'${path}')='array' AND json_array_length(${column},'${path}')>0) OR (json_type(${column},'${path}')='text' AND length(trim(json_extract(${column},'${path}')))>0))`}
function albumProfileCoverage(field:string){const path=`$.${field}`,row=db().prepare(`SELECT count(*) total,coalesce(sum(present),0) present FROM (SELECT f.album_key,min(CASE WHEN p.status='complete' AND json_valid(p.profile_json) AND ${present("p.profile_json",path)} THEN 1 ELSE 0 END) present FROM files f LEFT JOIN track_profiles p ON p.file_id=f.id GROUP BY f.album_key)`).get() as{total:number;present:number};return{present:Number(row.present),total:Number(row.total),missing:Number(row.total)-Number(row.present)}}
function albumTagCoverage(paths:string[]){const test=paths.map(path=>present("tags_json",path)).join(" OR "),row=db().prepare(`SELECT count(*) total,coalesce(sum(present),0) present FROM (SELECT album_key,min(CASE WHEN json_valid(tags_json) AND (${test}) THEN 1 ELSE 0 END) present FROM files GROUP BY album_key)`).get() as{total:number;present:number};return{present:Number(row.present),total:Number(row.total),missing:Number(row.total)-Number(row.present)}}
function creditCoverage(){const value=jsonState("credit_artwork").coverage as Record<string,{present?:number;total?:number}>|undefined;const result:Record<string,{present:number;total:number;missing:number}>={};for(const[key,source]of Object.entries(value??{})){const present=Number(source.present??0),total=Number(source.total??0);result[key]={present,total,missing:Math.max(0,total-present)}}return result}

export function snapshot(){
  const albums=rows("WITH a AS (SELECT album_key,CASE WHEN sum(status='error')>0 THEN 'failed' WHEN sum(status='written')=count(*) THEN 'complete' ELSE 'pending' END status FROM files GROUP BY album_key) SELECT status,count(*) count FROM a GROUP BY status"),ac=Object.fromEntries(albums.map(row=>[String(row.status),Number(row.count)])),entity="code||':'||coalesce(album_key,'file:'||file_id,'issue:'||id)",credits=creditCoverage(),semantic=categorizationSummary();
  return{semantic,metrics:{files:count("SELECT count(*) count FROM files"),enriched:count("SELECT count(*) count FROM files WHERE status='written'"),reprocessing:count("SELECT count(*) count FROM files WHERE status IN ('analyzed','processing')"),issues:count(`SELECT count(DISTINCT ${entity}) count FROM issues WHERE status='open'`),errors:count(`SELECT count(DISTINCT ${entity}) count FROM issues WHERE status='open' AND severity='error'`),albumsTotal:Object.values(ac).reduce((sum,value)=>sum+value,0),albumsComplete:ac.complete??0,albumsPending:ac.pending??0,albumsFailed:ac.failed??0},coverage:{genre:albumProfileCoverage("genre"),style:albumProfileCoverage("style"),mood:albumProfileCoverage("mood"),scene:albumProfileCoverage("scenes"),albumArtist:albumTagCoverage(["$.albumArtist","$.albumartist","$.extraProperties.ALBUMARTIST"]),artist:credits.artist??{present:0,total:0,missing:0},albumArtistImage:credits.albumArtist??{present:0,total:0,missing:0},composer:credits.composer??{present:0,total:0,missing:0}},paused:stateGet("paused")==="true",operational:{autostart:stateGet("scheduler_autostart",config.CURATOR_AUTOSTART)==="true",running:stateGet("scheduler_running")==="true",phase:stateGet("scheduler_phase","idle"),scan:jsonState("scan_progress"),processing:jsonState("processing_progress"),lastScan:Number(stateGet("last_scan","0")),lastError:stateGet("last_error")},files:rows("SELECT id,path,artist_name,album_name,status,updated_at FROM files ORDER BY updated_at DESC LIMIT 24"),issueGroups:rows(`SELECT code,severity,count(DISTINCT ${entity}) count,count(DISTINCT album_key) albums,max(message) sample FROM issues WHERE status='open' GROUP BY code,severity ORDER BY CASE severity WHEN 'error' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,count DESC`),failedAlbums:rows("SELECT f.album_key,min(f.artist_name) artist,min(f.album_name) album,count(*) tracks,max(i.message) message FROM files f LEFT JOIN issues i ON i.album_key=f.album_key AND i.code='processing_failed' AND i.status='open' WHERE f.status='error' GROUP BY f.album_key ORDER BY max(f.updated_at) DESC LIMIT 30"),jobs:rows("SELECT id,phase,status,subject,progress_json,detail,started_at,finished_at,created_at FROM jobs ORDER BY id DESC LIMIT 20"),taxonomy:rows("SELECT kind,name,aliases_json FROM taxonomy_terms WHERE active=1 ORDER BY kind,name"),proposals:rows("SELECT kind,display_name,occurrences FROM taxonomy_proposals ORDER BY occurrences DESC LIMIT 30"),sources:rows("SELECT provider,count(*) count,max(fetched_at) latest FROM evidence GROUP BY provider ORDER BY provider"),ai:rows("SELECT model,count(*) count,avg(confidence) confidence FROM enrichments GROUP BY model")}}
