import { versions } from "@/config";
import type { EnrichmentDecision, EvidenceFact } from "@/features/contracts/types";
import { enrichmentJsonSchema, enrichmentSchema } from "@/features/contracts/schema";
import { stableHash, wordLimit } from "@/features/scanner/normalize";
import { db } from "@/features/db/client";
import { enrichmentPrompt } from "./prompts";
import { recordAiUsage } from "@/features/ai/usage";
import { boundedEvidence } from "./evidence";
import { aiClient,aiModel } from "@/features/ai/client";
function key(value:string):string{return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function unique(values:string[]):string[]{return[...new Set(values.map(value=>value.trim()).filter(Boolean))]}
function canonicalize(result:EnrichmentDecision):EnrichmentDecision{
  const genres:string[]=[],styles=[...result.styles];
  for(const value of result.genres){const term=key(value);if(/^(alternatif et inde|alternativa e indie|alternative and indie|alternative indie|indie)$/.test(term))genres.push("Alternative");else if(term==="musiques du monde")genres.push("World");else if(term==="amerique latine")genres.push("Latin");else if(/^(latin pop|pop latino)$/.test(term)){genres.push("Latin","Pop");styles.push("Latin Pop")}else if(term==="new jack swing"){genres.push("R&B");styles.push("New Jack Swing")}else genres.push(value)}
  const cleanStyles=styles.flatMap(value=>{const term=key(value);if(/^(alternatif et inde|alternativa e indie|alternative and indie|alternative indie)$/.test(term))return["Indie"];if(["alternative","world","musiques du monde","amerique latine","latin"].includes(term))return[];if(/^(pop rock|poprock)$/.test(term))return["Pop Rock"];if(/^(folk rock|folkrock)$/.test(term))return["Folk Rock"];if(/^(country rock|countryrock)$/.test(term))return["Country Rock"];return[value]});
  const finalGenres=unique(genres).slice(0,2),finalStyles=unique(cleanStyles).slice(0,3),semantic=new Set([...finalGenres,...finalStyles].map(key));
  return{...result,genres:finalGenres,styles:finalStyles,moods:unique(result.moods).slice(0,3),scenes:unique(result.scenes).filter(scene=>!semantic.has(key(scene))).slice(0,2)}
}
function retryable(error: unknown): boolean { const status=Number((error as {status?:number})?.status??0);const name=(error as {name?:string})?.name??"";return status===408||status===409||status===429||status>=500||name.includes("Timeout"); }
async function invoke(prompt: string): Promise<EnrichmentDecision> { let lastError:unknown;for(let attempt=0;attempt<3;attempt+=1){try{const response=await aiClient.structured<EnrichmentDecision>({input:prompt,schemaName:"music_enrichment",schema:enrichmentJsonSchema});recordAiUsage("album_enrichment",aiModel,response);return enrichmentSchema.parse(response.data)}catch(error){lastError=error;if(!retryable(error)||attempt===2)break;await new Promise((resolve)=>setTimeout(resolve,1_000*(attempt+1)))}}throw lastError; }
export async function enrich(entityKey: string, artist: string, album: string, evidence: EvidenceFact[], taxonomy: Record<string, string[]>): Promise<EnrichmentDecision & { model: string }> { const safeEvidence=boundedEvidence(evidence);const evidenceHash=stableHash(safeEvidence.map(({retrievedAt:_retrievedAt,...fact})=>fact));const cached=db().prepare("SELECT model,result_json FROM enrichments WHERE entity_key=? AND evidence_hash=? AND prompt_version=? AND taxonomy_version=? ORDER BY id DESC LIMIT 1").get(entityKey,evidenceHash,versions.prompt,versions.taxonomy) as {model:string;result_json:string}|undefined;if(cached)return{...canonicalize(JSON.parse(cached.result_json) as EnrichmentDecision),model:cached.model};const prompt=enrichmentPrompt(artist,album,safeEvidence,taxonomy);const result=canonicalize(await invoke(prompt));result.artistDescription=wordLimit(result.artistDescription,60);result.albumDescription=wordLimit(result.albumDescription,50);db().prepare("INSERT INTO enrichments(entity_key,evidence_hash,model,result_json,confidence,prompt_version,taxonomy_version) VALUES (?,?,?,?,?,?,?)").run(entityKey,evidenceHash,aiModel,JSON.stringify(result),result.confidence,versions.prompt,versions.taxonomy);return{...result,model:aiModel}; }
