import { readdir,rm } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { dirname } from "node:path";
import { config,versions } from "@/config";
import { db,stateGet,stateSet } from "@/features/db/client";
import { runtimeSettings } from "@/features/settings/runtime";
import { scanLibrary } from "@/features/scanner/scan";
import { importedSinceLastPoll } from "@/features/sources/lidarr";
import { processAlbums } from "./process";
import { auditArtwork } from "@/features/analysis/artwork-audit";
import { ensureCreditImages } from "@/features/artwork/credits";
import { categorizationPendingCount,processCategorizationBatch } from "@/features/categorization/process";
import { clearAlbumLeases } from "@/features/scheduler/album-lease";
import { runPlaylistSchedule } from "@/features/playlists/schedule";
let running=false,creditRunning=false,timer:NodeJS.Timeout|undefined,actionTimer:NodeJS.Timeout|undefined;
const CREDIT_ARTWORK_INTERVAL=24*60*60_000;
const execute=promisify(execFile);
function acquireLease():boolean{const until=Number(stateGet("scheduler_lease","0"));if(until>Date.now())return false;stateSet("scheduler_lease",String(Date.now()+10*60_000));return true}
type JobProgress={subject:string;phase:string;currentFile?:string;processedCount:number;totalCount:number};
async function job<T>(phase:string,work:(report:(progress:JobProgress)=>void)=>Promise<T>):Promise<T>{const row=db().prepare("INSERT INTO jobs(phase,status,started_at,heartbeat_at) VALUES (?,'running',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id").get(phase) as{id:number};const report=(progress:JobProgress)=>db().prepare("UPDATE jobs SET subject=?,progress_json=?,heartbeat_at=CURRENT_TIMESTAMP WHERE id=? AND status='running'").run(progress.subject,JSON.stringify(progress),row.id);const pulse=setInterval(()=>db().prepare("UPDATE jobs SET heartbeat_at=CURRENT_TIMESTAMP WHERE id=? AND status='running'").run(row.id),15_000);try{const value=await work(report);db().prepare("UPDATE jobs SET status='complete',detail=?,heartbeat_at=CURRENT_TIMESTAMP,finished_at=CURRENT_TIMESTAMP WHERE id=?").run(JSON.stringify(value),row.id);return value}catch(error){db().prepare("UPDATE jobs SET status='failed',detail=?,error_detail=?,finished_at=CURRENT_TIMESTAMP WHERE id=?").run(String(error),String(error),row.id);throw error}finally{clearInterval(pulse)}}
async function cleanInterruptedTemps():Promise<void>{const paths=db().prepare("SELECT DISTINCT path FROM files WHERE status='processing'").all() as Array<{path:string}>;for(const dir of new Set(paths.map(row=>dirname(row.path)))){for(const entry of await readdir(dir).catch(()=>[]))if(entry.includes(".curator-"))await rm(`${dir}/${entry}`,{force:true})}}
async function recoverInterruptedWork():Promise<void>{await cleanInterruptedTemps();clearAlbumLeases();db().prepare("UPDATE jobs SET status='failed',detail='Interrupted or stale worker',error_detail='Worker heartbeat stopped',finished_at=CURRENT_TIMESTAMP WHERE status='running'").run();db().prepare("UPDATE files SET status='analyzed',updated_at=CURRENT_TIMESTAMP WHERE status='processing'").run();db().prepare("UPDATE files AS f SET status='analyzed',updated_at=CURRENT_TIMESTAMP WHERE status='error' AND EXISTS (SELECT 1 FROM issues i WHERE i.status='open' AND i.code='processing_failed' AND (i.file_id=f.id OR i.album_key=f.album_key)) AND NOT EXISTS (SELECT 1 FROM issues i WHERE i.status='open' AND i.code='scan_failed' AND i.file_id=f.id)").run();db().prepare("UPDATE files SET status='written',updated_at=CURRENT_TIMESTAMP WHERE status='analyzed' AND updated_at='1970-01-01' AND desired_hash IS NOT NULL").run();db().prepare("UPDATE issues SET status='resolved',updated_at=CURRENT_TIMESTAMP WHERE code='scan_failed' AND message LIKE '%/._%'").run();stateSet("scheduler_lease","0");stateSet("scheduler_running","false");stateSet("scheduler_phase","idle");stateSet("credit_artwork_running","false");stateSet("scheduler_autostart",config.CURATOR_AUTOSTART)}
function queuePolicyRefresh():void{const semanticVersion=`${versions.taxonomy}:${versions.prompt}`;if(stateGet("semantic_policy_version")!==semanticVersion){db().prepare("UPDATE files SET status='analyzed',updated_at=CURRENT_TIMESTAMP WHERE status='written' AND album_key IN (SELECT album_key FROM files GROUP BY album_key HAVING max(CASE WHEN json_valid(tags_json) THEN CASE WHEN json_type(tags_json,'$.style')='array' THEN json_array_length(tags_json,'$.style') WHEN json_type(tags_json,'$.style')='text' THEN length(trim(json_extract(tags_json,'$.style'))) ELSE 0 END ELSE 0 END)=0 OR max(CASE WHEN json_valid(tags_json) THEN CASE WHEN json_type(tags_json,'$.mood')='array' THEN json_array_length(tags_json,'$.mood') WHEN json_type(tags_json,'$.mood')='text' THEN length(trim(json_extract(tags_json,'$.mood'))) ELSE 0 END ELSE 0 END)=0)").run();stateSet("semantic_policy_version",semanticVersion)}if(stateGet("artwork_policy_version")!==String(versions.artwork)){db().prepare("UPDATE files SET status='analyzed',updated_at=CURRENT_TIMESTAMP WHERE status='written' AND album_key IN (SELECT DISTINCT album_key FROM issues WHERE status='open' AND code IN ('missing_album_artwork','missing_artist_artwork'))").run();stateSet("artwork_policy_version",String(versions.artwork))}if(stateGet("identity_policy_version")!==String(versions.identity)){db().prepare("UPDATE files SET status='analyzed',updated_at=CURRENT_TIMESTAMP WHERE status='written' AND album_key IN (SELECT DISTINCT album_key FROM issues WHERE status='open' AND code='identity_unresolved')").run();stateSet("identity_policy_version",String(versions.identity))}if(stateGet("provider_policy_version")!==String(versions.providers)){db().prepare("UPDATE issues SET code='processing_deferred',severity='warning',updated_at=CURRENT_TIMESTAMP WHERE status='open' AND code='processing_failed' AND (message LIKE '%Connection error%' OR message LIKE '%fetch failed%' OR message LIKE '%no router for requested model%' OR message LIKE '% 503 %' OR message LIKE '% 429 %')").run();db().prepare("UPDATE files SET status='analyzed',updated_at=CURRENT_TIMESTAMP WHERE status='written' AND album_key IN (SELECT DISTINCT album_key FROM issues WHERE status='open' AND code='processing_deferred')").run();db().prepare("UPDATE track_profiles SET next_retry_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE status IN ('partial','failed') AND last_error LIKE '%no router for requested model%'").run();stateSet("provider_policy_version",String(versions.providers))}const pending=(db().prepare("SELECT count(*) count FROM files WHERE status IN ('analyzed','processing','error')").get() as{count:number}).count;if(!pending&&stateGet("policy_version")!==String(versions.normalization)){db().prepare("UPDATE files SET status='analyzed',applied_hash=NULL,updated_at=CURRENT_TIMESTAMP WHERE status='written'").run();stateSet("policy_version",String(versions.normalization))}}
async function runUnicodeIntegrity():Promise<void>{const version=String(versions.normalization);if(stateGet("unicode_integrity_version")===version)return;stateSet("scheduler_phase","integrity");const result=await job("integrity",async report=>{report({subject:"Physical Unicode tags",phase:"integrity",processedCount:0,totalCount:0});const{stdout}=await execute(process.execPath,["scripts/repair-unicode-tags.mjs"],{cwd:process.cwd(),env:{...process.env,LANG:"C.UTF-8",LC_ALL:"C.UTF-8",REPAIR_WORKERS:"6"},maxBuffer:4*1024*1024});return JSON.parse(stdout)});stateSet("unicode_integrity",JSON.stringify(result));stateSet("unicode_integrity_version",version)}
function startCreditArtwork():void{const last=Number(stateGet("credit_artwork_last_run","0"));if(creditRunning||Date.now()-last<CREDIT_ARTWORK_INTERVAL)return;creditRunning=true;stateSet("credit_artwork_running","true");stateSet("credit_artwork_last_run",String(Date.now()));void ensureCreditImages(24).then(async result=>{stateSet("credit_artwork",JSON.stringify(result));const{stdout}=await execute(process.execPath,["scripts/backfill-artwork.mjs"],{cwd:process.cwd(),env:{...process.env,LANG:"C.UTF-8",LC_ALL:"C.UTF-8",ARTWORK_ALBUM_LIMIT:"40",ARTWORK_ARTIST_LIMIT:"200",ARTWORK_WORKERS:"6",ARTWORK_SKIP_MUSICBRAINZ:"true",ARTWORK_RETRY_MISSING:"false",ARTWORK_POLICY_VERSION:String(versions.artwork)},maxBuffer:4*1024*1024});stateSet("supplemental_artwork",stdout.trim());stateSet("credit_artwork_error","")}).catch(error=>stateSet("credit_artwork_error",String(error))).finally(()=>{creditRunning=false;stateSet("credit_artwork_running","false")})}
export async function runCycle(forceScan=false):Promise<void>{if(running||stateGet("paused")==="true"||!acquireLease())return;running=true;stateSet("scheduler_running","true");stateSet("last_error","");const lease=setInterval(()=>stateSet("scheduler_lease",String(Date.now()+10*60_000)),30_000);try{const settings=runtimeSettings();stateSet("scheduler_phase","poll");const lastScan=Number(stateGet("last_scan","0")),imported=await importedSinceLastPoll().catch(()=>false);if(forceScan||imported||Date.now()-lastScan>settings.scanIntervalHours*60*60_000){stateSet("scheduler_phase","scan");await job("scan",report=>{report({subject:"Music library",phase:"scan",processedCount:0,totalCount:0});return scanLibrary(report)});stateSet("last_scan",String(Date.now()))}if(stateGet("paused")==="true")return;queuePolicyRefresh();await runUnicodeIntegrity();let failure:unknown;const filePending=(db().prepare("SELECT count(*) count FROM files WHERE status='analyzed'").get() as{count:number}).count;if(filePending){stateSet("scheduler_phase","enrich");try{await job("enrich",report=>processAlbums(settings.enrichmentBatchAlbums,report))}catch(error){failure=error}}const semanticPending=categorizationPendingCount();if(semanticPending){stateSet("scheduler_phase","categorize");try{await job("categorize",report=>processCategorizationBatch(settings.categorizationBatchAlbums,report))}catch(error){failure??=error}}if(failure)throw failure;startCreditArtwork();if(stateGet("paused")==="true")return;stateSet("scheduler_phase","playlists");await runPlaylistSchedule();stateSet("scheduler_phase","artwork-audit");stateSet("artwork_audit",JSON.stringify(await auditArtwork()));stateSet("last_error","")}catch(error){stateSet("last_error",String(error))}finally{clearInterval(lease);stateSet("scheduler_phase","idle");stateSet("scheduler_running","false");stateSet("scheduler_lease","0");running=false;const filePending=(db().prepare("SELECT count(*) count FROM files WHERE status='analyzed'").get() as{count:number}).count,pending=filePending+categorizationPendingCount();if(pending&&stateGet("paused")!=="true")setTimeout(()=>void runCycle(false),30_000)}}
export function startScheduler():void{void recoverInterruptedWork().then(()=>{if(timer||config.CURATOR_AUTOSTART!=="true")return;setTimeout(()=>void runCycle(false),2_000);timer=setInterval(()=>void runCycle(false),5*60_000);actionTimer=setInterval(()=>{const action=stateGet("requested_action");if(!action||running)return;stateSet("requested_action","");void runCycle(action==="scan")},2_000)});process.once("SIGTERM",()=>{if(timer)clearInterval(timer);if(actionTimer)clearInterval(actionTimer)})}
