import type { ResolvedIdentity } from "@/features/contracts/types";
import { normalized } from "@/features/scanner/normalize";
import type { MbCandidate } from "@/features/sources/musicbrainz";
import { cleanArtistName,cleanCatalogText } from "@/features/sources/musicbrainz";
import type { AppleResult } from "@/features/sources/apple";
function similarity(a:string,b:string):number{const left=new Set(normalized(a).split(" ").filter(Boolean)),right=new Set(normalized(b).split(" ").filter(Boolean));if(!left.size||!right.size)return 0;return[...left].filter(word=>right.has(word)).length/new Set([...left,...right]).size}
function candidateArtist(candidate:MbCandidate):string{const credit=candidate["artist-credit"]?.[0];return credit?.artist.name||credit?.name||""}
function fingerprint(candidate:MbCandidate):string{return[normalized(cleanCatalogText(candidate.title)),normalized(cleanArtistName(candidateArtist(candidate))),candidate["first-release-date"]?.slice(0,4)??"",candidate["primary-type"]??"",...(candidate["secondary-types"]??[]).sort()].join("|")}
function typeWeight(candidate:MbCandidate,localAlbum:string):number{const primary=candidate["primary-type"]?.toLowerCase(),secondary=(candidate["secondary-types"]??[]).map(value=>value.toLowerCase());let value=primary==="album"?.05:primary==="single"?-.07:primary==="ep"?-.04:primary==="other"?-.05:0;if(!/\blive\b/i.test(localAlbum)&&secondary.includes("live"))value-=.04;if(!/\bcompilation\b/i.test(localAlbum)&&secondary.includes("compilation"))value-=.01;return value}
export function resolveIdentity(artist:string,album:string,candidates:MbCandidate[],apple:AppleResult[]):ResolvedIdentity{const semantic=new Map<string,MbCandidate>();for(const candidate of candidates){const key=fingerprint(candidate),previous=semantic.get(key);if(!previous||Number(candidate.score??0)>Number(previous.score??0))semantic.set(key,candidate)}const cleanAlbum=cleanCatalogText(album),cleanArtist=cleanArtistName(artist),ranked=[...semantic.values()].map(candidate=>{const name=candidateArtist(candidate),appleMatch=apple.filter(item=>similarity(cleanCatalogText(item.collectionName),cleanCatalogText(candidate.title))>.9&&similarity(cleanArtistName(item.artistName),cleanArtistName(name))>.9);let score=similarity(cleanAlbum,cleanCatalogText(candidate.title))*.5+similarity(cleanArtist,cleanArtistName(name))*.36+Math.min(Number(candidate.score??0)/100,1)*.05+typeWeight(candidate,cleanAlbum);if(appleMatch.length)score+=.03;const year=Number(candidate["first-release-date"]?.slice(0,4)),sameYear=appleMatch.some(item=>Number(item.releaseDate?.slice(0,4))===year);if(year&&sameYear)score+=.01;return{candidate,candidateArtist:name,score:Math.max(0,Math.min(score,1))}}).sort((a,b)=>b.score-a.score);const best=ranked[0],margin=best?best.score-(ranked[1]?.score??0):0;const semanticTags=[...(best?.candidate.genres??[]),...(best?.candidate.tags??[])].sort((a,b)=>(b.count??0)-(a.count??0)).slice(0,16).map(tag=>tag.name);return{artistId:best?.candidate["artist-credit"]?.[0]?.artist.id,releaseGroupId:best?.candidate.id,artist:best?.candidateArtist||artist,album:best?.candidate.title||album,date:best?.candidate["first-release-date"],confidence:best?.score??0,margin,evidence:best?["musicbrainz","musicbrainz-tags",...(apple.length?["apple"]:[])]:[],semanticTags}}
export function identityIsWritable(identity:ResolvedIdentity):boolean{return identity.confidence>=.9&&(identity.margin>=.02||identity.confidence>=.96)}
