import type { ResolvedIdentity } from "@/features/contracts/types";
import { normalized } from "@/features/scanner/normalize";
import type { MbCandidate } from "@/features/sources/musicbrainz";
import { candidateCatalogTitles,catalogTitleVariants,cleanArtistName,cleanCatalogText } from "@/features/sources/musicbrainz";
import type { AppleResult } from "@/features/sources/apple";
function similarity(a:string,b:string):number{const compare=(leftValue:string,rightValue:string)=>{const left=new Set(normalized(leftValue).split(" ").filter(Boolean)),right=new Set(normalized(rightValue).split(" ").filter(Boolean));if(!left.size||!right.size)return 0;return[...left].filter(word=>right.has(word)).length/new Set([...left,...right]).size},withoutArticle=(value:string)=>normalized(value).replace(/^(?:a|an|the)\s+/,"");return Math.max(compare(a,b),compare(withoutArticle(a),withoutArticle(b)))}
function artistSimilarity(a:string,b:string):number{const left=cleanArtistName(a),right=cleanArtistName(b),withoutArticle=(value:string)=>normalized(value).replace(/^the\s+/,"");return Math.max(similarity(left,right),similarity(withoutArticle(left),withoutArticle(right)))}
function creditNames(candidate:MbCandidate):string[]{return(candidate["artist-credit"]??[]).map(credit=>credit.artist.name||credit.name||"").filter(Boolean)}
function candidateArtist(candidate:MbCandidate):string{const credits=candidate["artist-credit"]??[];return credits.map(credit=>`${credit.artist.name||credit.name||""}${credit.joinphrase??""}`).join("").trim()}
function candidateArtistSimilarity(local:string,candidate:MbCandidate):number{return Math.max(0,artistSimilarity(local,candidateArtist(candidate)),...creditNames(candidate).map(name=>artistSimilarity(local,name)))}
function fingerprint(candidate:MbCandidate):string{return[normalized(cleanCatalogText(candidate.title)),normalized(candidate.disambiguation??""),normalized(cleanArtistName(candidateArtist(candidate))),candidate["first-release-date"]?.slice(0,4)??"",candidate["primary-type"]??"",...(candidate["secondary-types"]??[]).sort()].join("|")}
function typeWeight(candidate:MbCandidate,localAlbum:string):number{const primary=candidate["primary-type"]?.toLowerCase(),secondary=(candidate["secondary-types"]??[]).map(value=>value.toLowerCase()),localType=/\bmaxi[- ]?single|\bsingle\b/i.test(localAlbum)?"single":/\bep\b/i.test(localAlbum)?"ep":"album";let value=primary===localType?.05:0;if(!/\blive\b/i.test(localAlbum)&&secondary.includes("live"))value-=.04;if(!/\bcompilation\b/i.test(localAlbum)&&secondary.includes("compilation"))value-=.01;return value}
export function resolveIdentity(artist:string,album:string,candidates:MbCandidate[],apple:AppleResult[]):ResolvedIdentity{const semantic=new Map<string,MbCandidate>();for(const candidate of candidates){const key=fingerprint(candidate),previous=semantic.get(key);if(!previous||Number(candidate.score??0)>Number(previous.score??0))semantic.set(key,candidate)}const cleanArtist=cleanArtistName(artist),localAlbums=catalogTitleVariants(cleanArtist,album),ranked=[...semantic.values()].map(candidate=>{const name=candidateArtist(candidate),titles=candidateCatalogTitles(candidate).map(cleanCatalogText),candidateAlbum=titles.sort((a,b)=>Math.max(...localAlbums.map(local=>similarity(local,b)))-Math.max(...localAlbums.map(local=>similarity(local,a))))[0]??candidate.title,titleScore=Math.max(...localAlbums.map(local=>similarity(local,candidateAlbum))),appleMatch=apple.filter(item=>Math.max(...catalogTitleVariants(item.artistName,item.collectionName).map(title=>similarity(title,candidateAlbum)))>.9&&candidateArtistSimilarity(item.artistName,candidate)>.9);let score=titleScore*.5+candidateArtistSimilarity(cleanArtist,candidate)*.36+Math.min(Number(candidate.score??0)/100,1)*.05+typeWeight(candidate,album);if(appleMatch.length)score+=.03;const year=Number(candidate["first-release-date"]?.slice(0,4)),sameYear=appleMatch.some(item=>Number(item.releaseDate?.slice(0,4))===year);if(year&&sameYear)score+=.01;return{candidate,candidateArtist:name,candidateAlbum,score:Math.max(0,Math.min(score,1))}}).sort((a,b)=>b.score-a.score);const best=ranked[0],margin=best?best.score-(ranked[1]?.score??0):0;const semanticTags=[...(best?.candidate.genres??[]),...(best?.candidate.tags??[])].sort((a,b)=>(b.count??0)-(a.count??0)).slice(0,16).map(tag=>tag.name);return{artistId:best?.candidate["artist-credit"]?.[0]?.artist.id,releaseGroupId:best?.candidate.id,artist:best?.candidateArtist||artist,album:best?.candidateAlbum||album,date:best?.candidate["first-release-date"],confidence:best?.score??0,margin,evidence:best?["musicbrainz","musicbrainz-tags",...(apple.length?["apple"]:[])]:[],semanticTags}}
export function identityIsWritable(identity:ResolvedIdentity):boolean{return identity.confidence>=.9&&(identity.margin>=.02||identity.confidence>=.96)}
