import { createHash } from "node:crypto";
import { db } from "@/features/db/client";
import { versions } from "@/config";
import type { AlbumSemanticProfile,TrackSemanticProfile } from "./types";

const energyOrder=["very_low","low","medium","high","very_high"];
function top(profiles:TrackSemanticProfile[],field:keyof TrackSemanticProfile,max:number):string[]{const counts=new Map<string,number>();for(const profile of profiles)for(const value of (Array.isArray(profile[field])?profile[field] as string[]:[]))counts.set(value,(counts.get(value)??0)+1);return[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).filter(([,count],index)=>index<max&&count>=Math.max(1,Math.ceil(profiles.length*.18))).map(([value])=>value)}
function topScalar(profiles:TrackSemanticProfile[],field:keyof TrackSemanticProfile,max:number):string[]{const counts=new Map<string,number>();for(const profile of profiles){const value=profile[field];if(typeof value==="string"&&value)counts.set(value,(counts.get(value)??0)+1)}return[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,max).map(([value])=>value)}
function cohesion(profiles:TrackSemanticProfile[]):AlbumSemanticProfile["cohesion"]{const signatures=profiles.map(profile=>new Set([...profile.genre,...profile.style,...profile.mood]));let total=0,pairs=0;for(let i=1;i<signatures.length;i++){const a=signatures[i-1],b=signatures[i],union=new Set([...a,...b]);total+=union.size?[...a].filter(value=>b.has(value)).length/union.size:0;pairs++}const score=pairs?total/pairs:1;return score>.48?"cohesive":score>.22?"varied":"highly_varied"}

export function aggregateAlbum(albumKey:string):AlbumSemanticProfile|null{
  const rows=db().prepare("SELECT p.profile_json FROM track_profiles p JOIN files f ON f.id=p.file_id WHERE p.album_key=? AND p.status IN ('complete','partial') AND p.schema_version=? AND p.classifier_version=? AND coalesce(json_extract(p.provenance_json,'$.audioAnalyzer'),0)=? AND f.updated_at<=p.source_updated_at ORDER BY p.file_id").all(albumKey,versions.categorizationSchema,versions.categorizationPrompt,versions.audioAnalysis) as Array<{profile_json:string}>;if(!rows.length)return null;const profiles=rows.map(row=>JSON.parse(row.profile_json) as TrackSemanticProfile),energies=profiles.map(profile=>energyOrder.indexOf(profile.energy)).filter(index=>index>=0),result:AlbumSemanticProfile={genre:top(profiles,"genre",3),style:top(profiles,"style",6),mood:top(profiles,"mood",6),production:top(profiles,"production",5),scenes:top(profiles,"scenes",4),styleEra:top(profiles,"styleEra",3),texture:top(profiles,"texture",5),timbre:top(profiles,"timbre",5),vocalProfile:top(profiles,"vocalProfile",4),acousticElectronicCharacter:topScalar(profiles,"acousticElectronicCharacter",3),energyRange:energies.length?[energyOrder[Math.min(...energies)],energyOrder[Math.max(...energies)]]:[],cohesion:cohesion(profiles),tracks:profiles.length,summary:""};result.summary=`${result.cohesion.replaceAll("_"," ")} album profile spanning ${result.genre.join(", ")||"uncategorized music"}${result.style.length?` with ${result.style.join(", ")}`:""}.`;const json=JSON.stringify(result),hash=createHash("sha256").update(rows.map(row=>row.profile_json).join("\n")).digest("hex");db().prepare("INSERT INTO album_profiles(album_key,profile_json,track_profile_hash,schema_version,classifier_version) VALUES (?,?,?,?,?) ON CONFLICT(album_key) DO UPDATE SET profile_json=excluded.profile_json,track_profile_hash=excluded.track_profile_hash,schema_version=excluded.schema_version,classifier_version=excluded.classifier_version,updated_at=CURRENT_TIMESTAMP").run(albumKey,json,hash,versions.categorizationSchema,versions.categorizationPrompt);return result;
}
