const vocabularies:Record<string,readonly string[]>={
  mood:["joyful","uplifting","playful","euphoric","triumphant","celebratory","hopeful","warm","tender","romantic","sensual","comforting","intimate","serene","peaceful","meditative","dreamy","ethereal","nostalgic","wistful","introspective","reflective","bittersweet","melancholic","somber","lonely","heartbroken","dark","ominous","anxious","suspenseful","urgent","tense","angry","aggressive","defiant","mysterious","hypnotic","eerie","quirky","surreal"],
  groove:["straight","four_on_floor","breakbeat","syncopated","swing","shuffle","half_time","double_time","motorik","funk_groove","latin_clave","reggae_one_drop","dancehall","trap_triplet","polyrhythmic","free_time","rubato","two_step"],
  texture:["sparse","minimal","open","intimate","layered","dense","wall_of_sound","ambient","percussive","orchestral","evolving","chaotic"],
  timbre:["warm","bright","dark","airy","lush","clean","gritty","distorted","noisy","bass_heavy","sub_bass_heavy","glassy","metallic","woody","organic","synthetic","vintage","crisp","soft","harsh","smooth"],
  production:["raw","polished","lo_fi","hi_fi","dry","spacious","reverb_heavy","delay_heavy","compressed","dynamic","live_feel","studio_polished","vintage","modern","analog_feel","digital_clean","sample_based","heavily_processed"],
  vocalProfile:["instrumental","sparse_vocals","clean_sung","intimate","breathy","soft","powerful","belted","rap","spoken","chant","choral","screamed","growled","processed","vocoder_autotune","call_and_response","mixed_vocal_styles"],
  lyricalThemes:["love","desire","heartbreak","relationships","nostalgia","introspection","identity","existential","spirituality","faith","grief","loneliness","hope","celebration","nightlife","escapism","rebellion","social_commentary","politics","storytelling","humor","nature","travel","home","work","violence_conflict","empowerment","surrealism"],
  listeningContexts:["background","focus","reading","coding_work","morning","daytime","sunset","late_night","driving","commute","dinner","social","party","club","workout","running","relaxation","meditation","sleep","headphones","romantic","rainy_day","summer","winter"],
  dynamicCharacter:["compressed","steady","moderately_dynamic","highly_dynamic","crescendo_build","episodic"],
  structuralCharacter:["verse_chorus","repetitive_loop","build_drop","linear","through_composed","ambient_evolving","jam_improvised","suite_multi_section"],
  recordingTypes:["standard_track","studio_recording","live_recording","demo","alternate_take","alternate_version","acoustic_version","extended_mix","radio_edit","remix","cover_version","interlude","intro","outro","reprise","skit","spoken_piece","medley","field_recording","archival_recording"],
};

type Rule=[RegExp,string];
const rules:Record<string,Rule[]>={
  mood:[[/atmospheric/,"dreamy"],[/confident|assertive|determined/,"defiant"],[/confrontational/,"aggressive"],[/intense/,"urgent"],[/yearning/,"wistful"],[/restless/,"anxious"],[/festive|upbeat|exuberant/,"celebratory"],[/exhilarated/,"euphoric"],[/brooding/,"dark"],[/earnest|serious|focused|contemplative/,"reflective"],[/vulnerable/,"intimate"],[/optimistic/,"hopeful"]],
  groove:[[/bass_driven|bass_groove|rock_groove|rock_pulse|riff_pulse|ballad|gentle_pulse|subtle_pulse|heavy|propulsive|stomping|danceable|dance_oriented|repetitive|loop_based|mechanical/,"straight"],[/offbeat|ska/,"reggae_one_drop"],[/hip_hop/,"breakbeat"],[/loose_pulse|lilting|rolling/,"swing"],[/blues|slow_soul/,"shuffle"],[/dub/,"reggae_one_drop"]],
  texture:[[/full_band|full_ensemble|full_bodied|^full$|thick/,"dense"],[/spacious|expansive/,"open"],[/rhythmic/,"percussive"],[/guitar|riff|piano_led|acoustic_led/,"layered"],[/anthemic/,"wall_of_sound"],[/dynamic|sustained/,"evolving"],[/compact|restrained|delicate/,"minimal"],[/atmospheric|dub_space|cinematic/,"ambient"]],
  timbre:[[/distort|overdriven|crunch/,"distorted"],[/resonant|rounded|mellow|earthy|deep|warm/,"warm"],[/punchy|percussive|forceful|powerful|crisp/,"crisp"],[/clear|polished/,"clean"],[/abrasive/,"harsh"],[/muted/,"soft"],[/grainy|raspy/,"gritty"],[/brassy/,"bright"],[/bright/,"bright"]],
  production:[[/loud|radio_ready/,"compressed"],[/studio|multitrack|clean_pop/,"studio_polished"],[/room|ambience|concert/,"spacious"],[/live|naturalistic|organic_band/,"live_feel"],[/dub/,"delay_heavy"],[/electronic_program|studio_processed/,"heavily_processed"],[/guitar_forward|rhythm_section|prominent_|vocal_forward|beat_focused|wide_guitars|restrained_arrangement/,""]],
  vocalProfile:[[/instrumental/,"instrumental"],[/melodic|clean|solo_(?:lead_)?vocal|sung|lead_singing/,"clean_sung"],[/expressive|forceful|raspy|shouted/,"powerful"],[/backing|harmoni|duet|multiple_vocal|group_voice/,"mixed_vocal_styles"],[/restrained|intimate/,"intimate"],[/conversational|plainspoken/,"spoken"],[/rhythmic|rap|toasting/,"rap"]],
  lyricalThemes:[[/romance|affection|devotion|intimacy|commitment|emotional_connection/,"love"],[/longing|obsession/,"desire"],[/relationship|separation|emotional_distance/,"relationships"],[/isolation|alienation/,"loneliness"],[/regret|memory/,"nostalgia"],[/resilien|persever|optimism|aspiration/,"hope"],[/dance|party/,"nightlife"],[/disillusion|uncertainty|self_doubt|reflection|inner_conflict/,"introspection"],[/loss/,"grief"],[/mortality/,"existential"],[/freedom|resistance|defiance/,"rebellion"],[/anger|empower/,"empowerment"]],
  listeningContexts:[[/focused_work|coding/,"coding_work"],[/focus|active_listening/,"focus"],[/reflective|quiet|nostalgic|cathartic|classic_.*listening|rock_.*listening|casual_listening/,"headphones"],[/late_night|evening|urban_nightlife/,"late_night"],[/dancefloor|dancing/,"club"],[/road_trip|road_listening/,"driving"],[/concert|festival|sing_along|communal|social_gathering|live_.*atmosphere/,"social"],[/high_(?:energy|intensity)|rock_workout|heavy_music|energizing/,"workout"],[/romantic/,"romantic"],[/summer/,"summer"]],
  dynamicCharacter:[[/limited_dynamic|compress/,"compressed"],[/crescendo|build|gradual|rising|swell|lift/,"crescendo_build"],[/episodic|accent|chorus|climax|peaks/,"episodic"],[/highly_dynamic|live_dynamics/,"highly_dynamic"],[/moderate/,"moderately_dynamic"],[/steady|sustain|intensity|forceful|restrained|controlled|energetic|gentle|heavy|driving|strong/,"steady"]],
  structuralCharacter:[[/verse|refrain|hook|ballad_form|song_form/,"verse_chorus"],[/riff|repet|groove_centered|loop/,"repetitive_loop"],[/build_drop/,"build_drop"],[/gradual|layered_development|instrumental_(?:interlude|break|transition)|linear/,"linear"],[/ambient|texture_driven/,"ambient_evolving"],[/extended|jam|solo|improvis|concert_performance/,"jam_improvised"],[/contrasting|sectional|episodic|multi_section/,"suite_multi_section"]],
  recordingTypes:[[/concert|live_/,"live_recording"],[/field_record/,"field_recording"],[/archival/,"archival_recording"],[/album_track|album_version|instrumental|compilation|full_band|electric_|electronic_|stereo|multitrack|vocal_|ensemble|original_composition|sampling|soundtrack|programmed/,"standard_track"]],
};

export function controlledValues(field:string,values:string[]):string[]{
  const allowed=vocabularies[field];if(!allowed)return values;const set=new Set(allowed),output:string[]=[];
  for(const value of values){const mapped=rules[field]?.find(([pattern])=>pattern.test(value))?.[1]??value;if(mapped&&set.has(mapped)&&!output.includes(mapped))output.push(mapped)}return output;
}

export const canonicalPrompt=Object.entries(vocabularies).map(([field,values])=>`${field}: ${values.join(", ")}`).join("\n");
