import type { AudioFeatures,CategorizationFile,TrackSemanticProfile } from "./types";
import { normalizeList,normalizeProfile } from "./vocabulary";

function values(tags:Record<string,unknown>,...keys:string[]):string[]{for(const key of keys){const value=tags[key];if(Array.isArray(value))return value.map(String).filter(Boolean);if(typeof value==="string"&&value.trim())return value.split(/[;,|]/).map(item=>item.trim()).filter(Boolean)}return[]}
function level(value:number):TrackSemanticProfile["energy"]{return value<.18?"very_low":value<.36?"low":value<.62?"medium":value<.82?"high":"very_high"}
function tempo(bpm:number|null):TrackSemanticProfile["tempoFeel"]{if(!bpm)return"midtempo";return bpm<60?"very_slow":bpm<80?"slow":bpm<112?"midtempo":bpm<135?"brisk":bpm<170?"fast":"very_fast"}
function year(tags:Record<string,unknown>):number{const raw=values(tags,"year","date","releaseDate")[0]??"";return Number(raw.match(/\d{4}/)?.[0]??0)}
function era(value:number):string[]{if(!value)return["era_ambiguous"];const decade=Math.floor(value/10)*10;return[decade<1950?"pre_1950s":`${decade}s`]}
function recordingTypes(file:CategorizationFile):string[]{const text=`${values(file.tags,"title")[0]??""} ${file.path}`.toLowerCase(),result=["standard_track"];for(const[key,value]of [["live","live_recording"],["demo","demo"],["remix","remix"],["radio edit","radio_edit"],["extended","extended_mix"],["acoustic","acoustic_version"],["interlude","interlude"],["intro","intro"],["outro","outro"]] as const)if(text.includes(key))result.push(value);return result}

export function fallbackProfile(file:CategorizationFile,audio:AudioFeatures):TrackSemanticProfile{
  const genre=normalizeList(values(file.tags,"genre","genres","GENRE"),3),style=normalizeList(values(file.tags,"style","styles","STYLE"),5),mood=normalizeList(values(file.tags,"mood","moods","MOOD"),5),electronic=[...genre,...style].some(value=>/electro|house|techno|trance|ambient|synth|idm|jungle|dnb|dubstep/.test(value)),instrumental=/instrumental/i.test(values(file.tags,"title")[0]??"");
  return normalizeProfile({genre:genre.length?genre:["other"],style,mood,valence:"bittersweet_or_neutral",energy:level(audio.energy),bpm:audio.estimatedBpm,tempoFeel:tempo(audio.estimatedBpm),groove:audio.beatRegularity>.55?["straight"]:[],danceability:level(audio.danceability),texture:[audio.dynamicRangeDb>15?"dynamic":"layered"],timbre:[audio.highFrequencyRatio>.45?"bright":"warm"],production:[audio.dynamicRangeDb<7?"compressed":"dynamic"],acousticElectronicCharacter:electronic?"mostly_electronic":"acoustic_electronic_hybrid",vocalProfile:instrumental?["instrumental"]:[],instrumentation:[],languages:[],lyricalThemes:[],listeningContexts:audio.energy<.3?["relaxation"]:audio.danceability>.7?["party"]:[],scenes:normalizeList(values(file.tags,"scene","scenes","SCENE"),3).length?normalizeList(values(file.tags,"scene","scenes","SCENE"),3):["contemporary_music"],styleEra:era(year(file.tags)),musicalKey:values(file.tags,"key","initialKey","INITIALKEY")[0]??null,mode:null,meter:[],dynamicCharacter:[audio.dynamicRangeDb>14?"highly_dynamic":audio.dynamicRangeDb>8?"moderately_dynamic":"compressed"],structuralCharacter:[],recordingTypes:recordingTypes(file),summary:`A ${tempo(audio.estimatedBpm).replaceAll("_"," ")} track with ${level(audio.energy).replaceAll("_"," ")} perceived energy.`,evidenceNotes:["Deterministic fallback from embedded tags and local audio features; semantic retry scheduled."]});
}
