import { db } from "@/features/db/client";
import { versions } from "@/config";
import { semanticProfileSchema } from "./schema";
import { normalizeProfile } from "./vocabulary";
import { aggregateAlbum } from "./aggregate";
import { categorizationPendingCount } from "./context";
import type { TrackSemanticProfile } from "./types";

export const semanticDimensions=["genre","style","mood","valence","energy","bpm","tempoFeel","groove","danceability","texture","timbre","production","acousticElectronicCharacter","vocalProfile","instrumentation","languages","lyricalThemes","listeningContexts","scenes","styleEra","musicalKey","mode","meter","dynamicCharacter","structuralCharacter","recordingTypes"] as const;
export type CategorizationSummary={total:number;complete:number;partial:number;failed:number;pending:number;audioAnalyzed:number;albumsProfiled:number;recent:number;dimensions:Record<string,{present:number;total:number;missing:number}>};

export function categorizationSummary():CategorizationSummary{
  const total=(db().prepare("SELECT count(*) count FROM files").get() as{count:number}).count,current=db().prepare(`SELECT p.status,p.profile_json,p.updated_at FROM track_profiles p JOIN files f ON f.id=p.file_id WHERE p.schema_version=? AND p.classifier_version=? AND coalesce(json_extract(p.provenance_json,'$.audioAnalyzer'),0)=? AND f.updated_at<=p.source_updated_at AND p.status<>'pending' AND NOT (p.status IN ('partial','failed') AND coalesce(p.next_retry_at,CURRENT_TIMESTAMP)<=CURRENT_TIMESTAMP)`).all(versions.categorizationSchema,versions.categorizationPrompt,versions.audioAnalysis) as Array<{status:string;profile_json:string;updated_at:string}>,status=Object.fromEntries(["complete","partial","failed"].map(name=>[name,current.filter(row=>row.status===name).length])),rows=current.filter(row=>row.status==="complete"||row.status==="partial"),counts=Object.fromEntries(semanticDimensions.map(field=>[field,0])) as Record<string,number>;
  for(const row of rows){try{const profile=JSON.parse(row.profile_json) as Record<string,unknown>;for(const field of semanticDimensions){const value=profile[field];if(Array.isArray(value)?value.length>0:value!==null&&value!==undefined&&value!=="")counts[field]+=1}}catch{}}
  return{total,complete:Number(status.complete??0),partial:Number(status.partial??0),failed:Number(status.failed??0),pending:categorizationPendingCount(),audioAnalyzed:(db().prepare("SELECT count(*) count FROM audio_features WHERE analyzer_version=?").get(versions.audioAnalysis) as{count:number}).count,albumsProfiled:(db().prepare("SELECT count(*) count FROM album_profiles WHERE schema_version=? AND classifier_version=?").get(versions.categorizationSchema,versions.categorizationPrompt) as{count:number}).count,recent:current.filter(row=>Date.parse(`${row.updated_at}Z`)>=Date.now()-60*60_000).length,dimensions:Object.fromEntries(semanticDimensions.map(field=>[field,{present:counts[field],total,missing:Math.max(0,total-counts[field])}]))};
}

export function searchProfiles(search:string,status:string,limit:number,offset:number){
  const allowed=new Set(["all","complete","partial","failed","pending"]),filter=allowed.has(status)?status:"all",term=`%${search.trim()}%`,rows=db().prepare(`WITH semantic AS (SELECT f.id,f.path,f.artist_name artist,f.album_name album,coalesce(json_extract(f.tags_json,'$.title[0]'),json_extract(f.tags_json,'$.title'),replace(substr(f.path,instr(f.path,'/')+1),'.'||f.format,'')) title,CASE WHEN p.file_id IS NULL OR p.album_key<>f.album_key OR p.schema_version<>? OR p.classifier_version<>? OR coalesce(json_extract(p.provenance_json,'$.audioAnalyzer'),0)<>? OR p.status='pending' OR (p.status IN ('partial','failed') AND coalesce(p.next_retry_at,CURRENT_TIMESTAMP)<=CURRENT_TIMESTAMP) OR f.updated_at>p.source_updated_at THEN 'pending' ELSE p.status END status,p.profile_json,p.manual_json,p.last_error,p.updated_at FROM files f LEFT JOIN track_profiles p ON p.file_id=f.id) SELECT * FROM semantic WHERE (?='' OR artist LIKE ? OR album LIKE ? OR path LIKE ? OR coalesce(profile_json,'') LIKE ?) AND (?='all' OR status=?) ORDER BY CASE status WHEN 'failed' THEN 0 WHEN 'partial' THEN 1 WHEN 'pending' THEN 2 ELSE 3 END,artist,album,path LIMIT ? OFFSET ?`).all(versions.categorizationSchema,versions.categorizationPrompt,versions.audioAnalysis,search.trim(),term,term,term,term,filter,filter,Math.min(100,Math.max(1,limit)),Math.max(0,offset)) as Array<Record<string,unknown>>;
  return rows.map(row=>({...row,profile:row.profile_json?JSON.parse(String(row.profile_json)):null,manual:row.manual_json?JSON.parse(String(row.manual_json)):{},profile_json:undefined,manual_json:undefined}));
}

export function saveProfileOverride(fileId:number,patch:Record<string,unknown>):void{
  const parsed=semanticProfileSchema.partial().parse(patch),row=db().prepare("SELECT f.album_key,p.profile_json FROM files f JOIN track_profiles p ON p.file_id=f.id WHERE f.id=?").get(fileId) as{album_key:string;profile_json:string}|undefined;if(!row)throw new Error("Track has not been categorized yet");const current=semanticProfileSchema.parse(JSON.parse(row.profile_json)),profile=semanticProfileSchema.parse({...current,...parsed} as TrackSemanticProfile),json=JSON.stringify(parsed);db().transaction(()=>{db().prepare("INSERT INTO track_profile_overrides(file_id,patch_json) VALUES (?,?) ON CONFLICT(file_id) DO UPDATE SET patch_json=excluded.patch_json,updated_at=CURRENT_TIMESTAMP").run(fileId,json);db().prepare("UPDATE track_profiles SET profile_json=?,manual_json=?,status='complete',next_retry_at=NULL,last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE file_id=?").run(JSON.stringify(profile),json,fileId);db().prepare("UPDATE issues SET status='resolved',updated_at=CURRENT_TIMESTAMP WHERE file_id=? AND code IN ('categorization_partial','categorization_failed')").run(fileId)})();aggregateAlbum(row.album_key);
}

export function retryCategorization(all=false):number{return db().prepare(all?"UPDATE track_profiles SET schema_version=0,status='pending',next_retry_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP":"UPDATE track_profiles SET status='pending',next_retry_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE status IN ('partial','failed')").run().changes}
