"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect,useState } from "react";
import { Activity,Archive,Disc3,House,ListMusic,LogOut,MoreHorizontal,PlusCircle,Settings,X } from "lucide-react";
import type { CuratorUser } from "@/features/auth/session";
const destinations=[{href:"/home",name:"Home",icon:House,description:"A mix made for you"},{href:"/library",name:"Library",icon:Disc3,description:"Browse and edit music"},{href:"/playlists",name:"Playlists",icon:ListMusic,description:"Design nightly mixes"},{href:"/add",name:"Add Music",icon:PlusCircle,description:"Find and queue albums"},{href:"/curator",name:"Curator",icon:Activity,description:"Automation and health"}];
const title=(path:string)=>destinations.find(item=>path.startsWith(item.href))?.name??(path.startsWith("/settings")?"Settings":"Music Curator");
export function AppShell({user,children}:{user:CuratorUser;children:React.ReactNode}){const path=usePathname(),[more,setMore]=useState(false);useEffect(()=>setMore(false),[path]);async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}return <div className="app-frame"><aside className="app-sidebar"><div className="brand"><div className="brand-mark"><Archive/></div><div className="brand-copy"><span>Personal archive</span><strong>Music Curator</strong></div></div><nav>{destinations.map(({href,name,icon:Icon,description})=><Link key={href} href={href} className={path.startsWith(href)?"active":""}><Icon/><span><strong>{name}</strong><small>{description}</small></span></Link>)}</nav><div className="account-panel"><span>{user.displayName.slice(0,1).toUpperCase()}</span><div><strong>{user.displayName}</strong><small>{user.tokenStatus==="active"?"Navidrome connected":"Sign in again required"}</small></div><Link href="/settings" aria-label="Settings"><Settings/></Link></div></aside><main className="app-content"><header className="app-topbar"><div><span className="kicker">Music Curator</span><h1>{title(path)}</h1></div><div className="top-user"><span>{user.displayName}</span><Link href="/settings" aria-label="Open settings"><Settings/></Link></div></header><div className="app-page">{children}</div></main><nav className="mobile-nav" aria-label="Primary">{destinations.slice(0,4).map(({href,name,icon:Icon})=><Link key={href} href={href} className={path.startsWith(href)?"active":""}><Icon/><span>{name.replace(" Music","")}</span></Link>)}<button onClick={()=>setMore(true)} className={more||path.startsWith("/curator")||path.startsWith("/settings")?"active":""}><MoreHorizontal/><span>More</span></button></nav>{more&&<div className="mobile-sheet-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setMore(false)}><section className="mobile-sheet" role="dialog" aria-modal="true" aria-label="More navigation"><header><div><span className="kicker">Signed in as</span><strong>{user.displayName}</strong></div><button onClick={()=>setMore(false)} aria-label="Close menu"><X/></button></header><Link href="/curator"><Activity/>Curator</Link><Link href="/settings"><Settings/>Settings</Link><button onClick={()=>void logout()}><LogOut/>Sign out</button></section></div>}</div>}
