"use client";
import { AlertTriangle,CheckCircle2,Database,Pause,Play,RefreshCw,RotateCcw,ScanLine,SlidersHorizontal,Sparkles } from "lucide-react";
import { LibraryIssues } from "@/components/library-issues";
import { StackCards } from "@/components/stack-cards";
import { AcquisitionPanel } from "@/components/acquisition-panel";

type Job={phase:string;status:string;subject:string;progress_json?:string;processedCount?:number;totalCount?:number};
type Summary={paused:boolean;metrics:Record<string,number>;operational:{running:boolean;phase:string;lastError?:string};jobs?:Job[]};

export function CuratorConsole({data,busy,action}:{data:Summary|null;busy:boolean;action:(name:string)=>void}){
  const pending=Number(data?.metrics?.albumsPending??0),issues=Number(data?.metrics?.issues??0),written=Number(data?.metrics?.written??data?.metrics?.enriched??0),files=Number(data?.metrics?.files??data?.metrics?.indexedFiles??0),percent=files?Math.min(100,Math.round(written/files*100)):0,active=(data?.jobs??[]).filter(job=>job.status==="running").map(job=>{try{return{...job,...JSON.parse(job.progress_json??"{}") as Partial<Job>}}catch{return job}}),state=data?.paused?"paused":data?.operational.running?"working":"ready";
  const title=state==="paused"?"Automation is paused":state==="working"?"Curator is working":"Your library is in sync",description=state==="paused"?"New imports are safe, but automatic processing will wait until you resume.":state==="working"?`Processing ${data?.operational.phase||"library updates"}. You can leave this page.`:`${files.toLocaleString()} tracks are indexed and automatic monitoring is on.`;
  return <div className="curator-workspace">
    <section className={`curator-overview paper ${state}`}><div className="curator-state"><span className={`state-orb ${state}`}>{state==="ready"?<CheckCircle2/>:state==="working"?<Sparkles/>:<Pause/>}</span><div><span className="kicker">Automation</span><h2>{title}</h2><p>{description}</p></div></div><div className="curator-actions"><button className="secondary-button" disabled={busy||!data} onClick={()=>action(data?.paused?"resume":"pause")}>{data?.paused?<Play/>:<Pause/>}{data?.paused?"Resume":"Pause"}</button><button className="primary-button" disabled={busy||(!data?.paused&&Boolean(data?.operational.running))} onClick={()=>action("scan")}><ScanLine/>Scan now</button></div></section>
    {data?.operational.lastError&&<div className="error-banner"><AlertTriangle/><div><strong>The last cycle needs attention</strong><p>{data.operational.lastError}</p></div></div>}
    <section className="curator-metrics"><article className="paper completion-card"><div className="metric-head"><span><Sparkles/>Enrichment</span><strong>{percent}%</strong></div><div className="completion-track"><i style={{width:`${percent}%`}}/></div><p>{written.toLocaleString()} of {files.toLocaleString()} files complete</p></article><article className="paper curator-stat"><Database/><div><strong>{files.toLocaleString()}</strong><span>Indexed tracks</span></div></article><article className={`paper curator-stat ${pending?"warning":"clear"}`}><ScanLine/><div><strong>{pending.toLocaleString()}</strong><span>Albums remaining</span></div></article><article className={`paper curator-stat ${issues?"danger":"clear"}`}><AlertTriangle/><div><strong>{issues.toLocaleString()}</strong><span>Open issues</span></div></article></section>
    {active.length?<section className="active-jobs"><div className="section-heading"><div><span className="kicker">Live work</span><h3>Processing now</h3></div><small>Safe to close this page</small></div>{active.map((job,index)=>{const total=job.totalCount??0,done=job.processedCount??0;return <article key={`${job.phase}-${index}`}><div><strong>{job.subject||job.phase}</strong><span>{job.phase}</span></div><progress max={Math.max(1,total)} value={done}/><small>{total?`${done} of ${total}`:"Working"}</small></article>})}</section>:null}
    <section className="stack-section"><div className="section-heading"><div><span className="kicker">Connected services</span><h3>Music stack</h3></div><span className="section-note">Updates independently every 15 seconds</span></div><StackCards/></section>
    <AcquisitionPanel/>
    <LibraryIssues/>
    <details className="maintenance-panel paper"><summary><span><SlidersHorizontal/><strong>Advanced maintenance</strong></span><small>Manual retries and cache controls</small></summary><div><button onClick={()=>action("retry-errors")} disabled={busy}><RotateCcw/>Retry errors</button><button onClick={()=>action("retry-categorization")} disabled={busy}><Sparkles/>Retry incomplete profiles</button><button onClick={()=>action("clear-cache")} disabled={busy}><RefreshCw/>Refresh source cache</button></div></details>
  </div>
}
