import { AlertTriangle,CheckCircle2,Disc3,FileAudio,Sparkles } from "lucide-react";
import type { Snapshot } from "./dashboard-types";
import { issueCopy } from "./dashboard-types";
import { SemanticCoverage } from "./semantic-library";
const number=(value:unknown)=>Number(value??0).toLocaleString();
function jobDetail(value:unknown):string{try{const detail=JSON.parse(String(value));return Object.entries(detail).map(([key,item])=>`${key} ${item}`).join(" / ")}catch{return String(value??"No detail")}}
export function Overview({data,retry,busy}:{data:Snapshot;retry:()=>void;busy:boolean}){
  const done=data.metrics.albumsComplete??0,total=data.metrics.albumsTotal||1,percent=Math.round(done/total*100),current=data.operational.processing,refreshing=data.metrics.reprocessing??0;
  const cards=[["Albums complete",done,CheckCircle2,"Metadata written and converged"],["Albums remaining",data.metrics.albumsPending,Disc3,"Queued for autonomous processing"],["Tracks enriched",data.metrics.enriched,Sparkles,`of ${number(data.metrics.files)} indexed files`],["Albums blocked",data.metrics.albumsFailed,AlertTriangle,"Retryable processing failures"]] as const;
  return <div className="dashboard-stack"><section className="progress-hero paper"><div><p className="eyebrow">Library completion</p><div className="progress-number">{percent}<span>%</span></div></div><div className="progress-copy"><h3>{refreshing?`${number(refreshing)} tracks are receiving richer metadata`:done===total?"The archive is fully curated":`${number(total-done)} albums still moving through the pipeline`}</h3><p>{refreshing?"Completed albums keep their completion credit while Curator adds missing styles, moods, scenes, album artists, and artwork in safe album batches.":"Completion means every track in an album has reached its desired metadata state. File-level warnings are grouped below so repeated tag issues do not obscure progress."}</p><div className="progress-track"><span style={{width:`${percent}%`}}/></div><div className="progress-legend"><span>{number(done)} complete</span><span>{number(total)} total albums</span></div></div></section>
  <section className="metric-grid">{cards.map(([label,value,Icon,detail])=><article key={label} className="metric-card paper"><div className="metric-icon"><Icon size={19}/></div><p className="metric-value">{number(value)}</p><h3>{label}</h3><p>{detail}</p></article>)}</section>
  <Coverage data={data}/><SemanticCoverage data={data.semantic}/>
  <section className="overview-grid"><article className="paper now-card"><Heading eyebrow="Live worker" title="What is happening now"><span className={`state-pill ${data.paused?"paused":data.operational.running?"running":"idle"}`}>{data.paused?"Paused":data.operational.running?"Working":"Idle"}</span></Heading>{data.operational.running?<div className="current-album"><div className="record-spin"><Disc3/></div><div><strong>{String(current.album??data.operational.phase)}</strong><p>{current.artist?`${current.artist} / album ${current.current} of ${current.total} in this batch`:"Preparing the next pipeline phase"}</p></div></div>:<Empty/>}</article>
  <article className="paper attention-card"><Heading eyebrow="Attention" title="Failures that need a retry"><span className="count-badge">{number(data.metrics.albumsFailed)}</span></Heading>{data.failedAlbums.length?<>{data.failedAlbums.slice(0,3).map(row=><div className="failed-row" key={String(row.album_key)}><FileAudio size={17}/><div><strong>{String(row.artist)} / {String(row.album)}</strong><p>{String(row.message??"Processing failed")}</p></div></div>)}<button className="action-button secondary full" disabled={busy} onClick={retry}>Retry all failed albums</button></>:<Empty/>}</article></section>
  <section className="overview-grid"><article className="paper section-card"><Heading eyebrow="Grouped signals" title="Library health"><span className="quiet-count">{number(data.metrics.issues)} open groups</span></Heading><div className="issue-groups">{data.issueGroups.slice(0,5).map(row=>{const copy=issueCopy[String(row.code)]??{title:String(row.code),detail:String(row.sample)};return <div className="issue-group" key={String(row.code)}><span className={`severity-dot ${row.severity}`}/><div><strong>{copy.title}</strong><p>{copy.detail}</p></div><div className="issue-count"><strong>{number(row.albums??row.count)}</strong><span>albums</span></div></div>})}</div></article>
  <article className="paper section-card"><Heading eyebrow="Activity log" title="Recent runs"/><div className="job-list">{data.jobs.slice(0,5).map(row=><div className="job-row" key={String(row.id)}><span className={`job-mark ${row.status}`}/><div><strong>{String(row.phase)} <span>#{String(row.id)}</span></strong><p>{jobDetail(row.detail)}</p></div><time>{String(row.status)}</time></div>)}</div></article></section></div>;
}
function Coverage({data}:{data:Snapshot}){const items=[["genre","Genres","albums"],["style","Styles","albums"],["mood","Moods","albums"],["scene","Scenes","albums"],["albumArtist","Album artist tags","albums"],["artist","Artist images","artists"],["albumArtistImage","Album-artist images","artists"],["composer","Composer images","composers"]] as const;return <section className="paper coverage-card"><Heading eyebrow="Metadata coverage" title="What Curator has actually completed"><span className="quiet-count">Scenes are evidence-based and optional</span></Heading><div className="coverage-grid">{items.map(([key,label,unit])=>{const value=data.coverage[key];if(!value?.total)return null;const percent=Math.round(value.present/value.total*100);return <article className="coverage-item" key={key}><div><strong>{label}</strong><span>{percent}%</span></div><div className="coverage-track"><span style={{width:`${percent}%`}}/></div><p>{number(value.present)} of {number(value.total)} {unit}<b>{value.missing?`${number(value.missing)} missing`:"Complete"}</b></p></article>})}</div></section>}
function Heading({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div>{children}</div>}
function Empty(){return <div className="empty-state"><CheckCircle2/><div><strong>No active blockers</strong><p>The autonomous scheduler will pick up pending work.</p></div></div>}
