import { AlertTriangle,CheckCircle2,Clock3,Database,FileAudio,Tags } from "lucide-react";
import type { Row,Snapshot } from "./dashboard-types";
import { issueCopy } from "./dashboard-types";
import { DuplicateReview } from "./duplicate-review";
const text=(value:unknown)=>String(value??"");
const compactPath=(path:unknown)=>text(path).replace(/^\/music\//,"");
function parseDetail(value:unknown):string{try{const data=JSON.parse(text(value));return Object.entries(data).map(([key,item])=>`${key}: ${item}`).join(" / ")}catch{return text(value)||"No additional detail"}}
export function LibraryView({rows}:{rows:Row[]}){return <div className="dashboard-stack"><Panel eyebrow="Latest files" title="Recently inspected"><div className="record-list">{rows.map(row=><div className="record-row" key={text(row.id)}><div className="file-icon"><FileAudio size={18}/></div><div><strong>{text(row.artist_name)} / {text(row.album_name)}</strong><p title={text(row.path)}>{compactPath(row.path)}</p></div><Status value={text(row.status)}/></div>)}</div></Panel><DuplicateReview/></div>}
export function IssuesView({data,retry,busy}:{data:Snapshot;retry:()=>void;busy:boolean}){return <div className="dashboard-stack"><Panel eyebrow="Health signals" title="Issues, grouped by cause"><p className="intro-copy">One missing field on a twelve-track album creates twelve file-level signals. Groups below show the underlying work instead of repeating the same message per track.</p><div className="issue-catalog">{data.issueGroups.map(row=>{const copy=issueCopy[text(row.code)]??{title:text(row.code),detail:text(row.sample)};return <article key={text(row.code)}><div className={`catalog-icon ${row.severity}`}><AlertTriangle size={18}/></div><div><h4>{copy.title}</h4><p>{copy.detail}</p><span>{text(row.albums)} albums affected</span></div><strong>{Number(row.count).toLocaleString()}</strong></article>})}</div></Panel>{data.failedAlbums.length>0&&<Panel eyebrow="Actionable" title="Failed albums"><div className="failed-table">{data.failedAlbums.map(row=><div key={text(row.album_key)}><div><strong>{text(row.artist)}</strong><p>{text(row.album)} / {text(row.tracks)} tracks</p></div><code>{text(row.message)}</code></div>)}</div><button className="action-button primary" disabled={busy} onClick={retry}>Retry failed albums</button></Panel>}</div>}
export function ProcessingView({data}:{data:Snapshot}){return <Panel eyebrow="Pipeline" title="Processing history"><div className="timeline">{data.jobs.map(row=><div className="timeline-row" key={text(row.id)}><div className={`timeline-icon ${row.status}`}>{row.status==="complete"?<CheckCircle2/>:row.status==="failed"?<AlertTriangle/>:<Clock3/>}</div><div><h4>{text(row.phase)} <span>run #{text(row.id)}</span></h4><p>{parseDetail(row.detail)}</p><time>{text(row.started_at||row.created_at)}{row.finished_at?` to ${text(row.finished_at)}`:" / in progress"}</time></div><Status value={text(row.status)}/></div>)}</div></Panel>}
export function TaxonomyView({data}:{data:Snapshot}){return <div className="taxonomy-grid">{["genre","style","mood","scene"].map(kind=><Panel key={kind} eyebrow="Canonical vocabulary" title={`${kind}s`}><div className="tag-cloud">{data.taxonomy.filter(row=>row.kind===kind).map(row=><span key={text(row.name)}><Tags size={12}/>{text(row.name)}</span>)}</div></Panel>)}</div>}
export function SourcesView({data}:{data:Snapshot}){return <div className="overview-grid"><Panel eyebrow="Factual evidence" title="Source cache">{data.sources.map(row=><SourceRow key={text(row.provider)} name={text(row.provider)} count={Number(row.count)} detail={`Latest ${text(row.latest)}`}/>)}</Panel><Panel eyebrow="Semantic decisions" title="AI routing">{data.ai.map(row=><SourceRow key={text(row.model)} name={text(row.model)} count={Number(row.count)} detail={`${Math.round(Number(row.confidence)*100)}% average confidence`}/>)}</Panel></div>}
function SourceRow({name,count,detail}:{name:string;count:number;detail:string}){return <div className="source-row"><Database size={18}/><div><strong>{name}</strong><p>{detail}</p></div><span>{count.toLocaleString()}</span></div>}
function Status({value}:{value:string}){return <span className={`status-label ${value}`}>{value}</span>}
function Panel({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="paper section-card"><div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div></div>{children}</section>}
