"use client";

import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { CheckCircle2,ExternalLink,ImageIcon,LoaderCircle,Search,Upload,X } from "lucide-react";
import { issueCopy } from "./dashboard-types";

type Issue={id:number;code:string;severity:string;message:string;album_key:string|null;artist:string|null;album:string|null;tracks:number;updated_at:string};
type Duplicate={group_key:string;artist:string;album:string;kind:string;confidence:number;status:string;detail_json:string;updated_at:string};
type ResponseData={issues:Issue[];issueCounts:Record<string,number>;total:number;duplicates:Duplicate[]};
type Suggestion={id:string;kind:"identity"|"cover"|"artist";label:string;provider:string;confidence:number;evidence:string;sourcePage:string;imageUrl?:string;artist?:string;album?:string;date?:string;artistMbid?:string;releaseGroupMbid?:string;facts?:string[]};
type Original={artist:string;album:string;date:string;tracks:number;genres:string[];artistMbid:string;releaseGroupMbid:string};
type Coverage={present:number;total:number;missing:number};
type SemanticSummary={complete:number;partial:number;failed:number;pending:number;dimensions:Record<string,Coverage>};
type Summary={coverage:Record<string,Coverage>;semantic:SemanticSummary};
const filters=[["review","Needs review"],["failed","Failures"],["identity","Catalog matches"],["missing-artwork","Artwork"],["duplicates","Duplicates"],["metadata","Metadata coverage"],["deferred","Waiting automatically"],["all","All issues"]];
function suggestionKind(issue:Issue):"identity"|"cover"|"artist"{if(issue.code==="missing_artist_artwork")return"artist";if(issue.code.includes("artwork")||issue.code==="missing_embedded_art")return"cover";return"identity"}
function canReview(issue:Issue){return Boolean(issue.album_key)&&(issue.code==="identity_unresolved"||issue.code==="missing_albumArtist"||issue.code.includes("artwork")||issue.code==="missing_embedded_art")}
async function responseBody(response:Response):Promise<{error?:string;suggestions?:Suggestion[];original?:Original}> {const text=await response.text();if(!text)return{error:`Request failed (${response.status})`};try{return JSON.parse(text) as{error?:string;suggestions?:Suggestion[];original?:Original}}catch{return{error:`The server returned an unreadable response (${response.status})`}}}

export function LibraryIssues(){
  const[filter,setFilter]=useState("review"),[query,setQuery]=useState(""),[data,setData]=useState<ResponseData>({issues:[],issueCounts:{},total:0,duplicates:[]});
  const[summary,setSummary]=useState<Summary|null>(null);
  const[editing,setEditing]=useState<Issue|null>(null),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[original,setOriginal]=useState<Original|null>(null),[loading,setLoading]=useState(false),[applying,setApplying]=useState<string|null>(null),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const apiFilter=filter==="review"?"all":filter,[issuesResponse,summaryResponse]=await Promise.all([fetch(`/api/library/issues?filter=${apiFilter}&limit=5000`,{cache:"no-store"}),fetch("/api/summary",{cache:"no-store"})]);if(issuesResponse.ok)setData(await issuesResponse.json());if(summaryResponse.ok)setSummary(await summaryResponse.json())},[filter]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(!editing?.album_key)return;setLoading(true);setSuggestions([]);setOriginal(null);setNotice("");const params=new URLSearchParams({albumKey:editing.album_key,kind:suggestionKind(editing)});fetch(`/api/library/suggestions?${params}`,{cache:"no-store"}).then(async response=>{const body=await responseBody(response);if(!response.ok)throw new Error(body.error||"Suggestion lookup failed");setSuggestions(body.suggestions||[]);setOriginal(body.original||null)}).catch(error=>setNotice(error instanceof Error?error.message:"Suggestion lookup failed")).finally(()=>setLoading(false))},[editing]);
  const needle=query.trim().toLocaleLowerCase(),issues=useMemo(()=>data.issues.filter(item=>(filter!=="review"||canReview(item))&&(!needle||`${item.artist} ${item.album} ${item.code} ${item.message}`.toLocaleLowerCase().includes(needle))),[data.issues,filter,needle]),duplicates=useMemo(()=>data.duplicates.filter(item=>!needle||`${item.artist} ${item.album}`.toLocaleLowerCase().includes(needle)),[data.duplicates,needle]);
  async function applySuggestion(suggestion:Suggestion){if(!editing?.album_key)return;setApplying(suggestion.id);setNotice("");try{const response=await fetch("/api/library/suggestions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:suggestion.id})}),body=await responseBody(response);if(!response.ok)return setNotice(body.error||"Could not apply suggestion");setEditing(null);await load()}catch{setNotice("Could not reach Curator. Please retry.")}finally{setApplying(null)}}
  async function applyManual(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing?.album_key)return;setApplying("manual");setNotice("");try{const form=new FormData(event.currentTarget);form.set("albumKey",editing.album_key);const response=await fetch("/api/library/manual",{method:"POST",body:form}),body=await responseBody(response);if(!response.ok)return setNotice(body.error||"Manual update failed");setEditing(null);await load()}catch{setNotice("Could not reach Curator. Please retry.")}finally{setApplying(null)}}
  return <>
    <section className="paper library-workbench"><div className="section-heading"><div><p className="eyebrow">Review queue</p><h2>Items that need a decision</h2><p className="library-intro">Automatic work stays out of this list. Anything shown here benefits from your review.</p></div><label className="library-search"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search reviews" aria-label="Search library issues"/></label></div>
      <div className="filter-bar" aria-label="Library filters">{filters.map(([value,label])=><button key={value} className={filter===value?"filter-active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div>
      <CoverageContext filter={filter} summary={summary}/>
      {filter==="duplicates"?<div className="issue-list">{duplicates.map(item=><article className="issue-row" key={item.group_key}><div><strong>{item.album}</strong><p>{item.artist}</p><small>{item.kind} · {Math.round(item.confidence*100)}% confidence</small></div><span className="status-pill warning">{item.status}</span></article>)}{!duplicates.length&&<Empty/>}</div>:
      <div className="issue-list">{issues.map(item=>{const copy=issueCopy[item.code]??{title:item.code.replaceAll("_"," "),detail:item.message},detail=item.message&&item.message!==copy.detail?item.message:copy.detail;return <article className="issue-row actionable-row" key={`${item.code}:${item.id}:${item.album_key}`}><div className="issue-copy"><div className="issue-title"><strong>{item.album||copy.title}</strong><span className={`status-pill ${item.severity}`}>{copy.title}</span></div><p>{item.artist||"Library-level issue"}</p><small>{detail}</small></div>{canReview(item)&&<button className="btn-primary compact" onClick={()=>setEditing(item)}><Search size={16}/>Review</button>}</article>})}{!issues.length&&<Empty filter={filter} summary={summary}/>}</div>}
    </section>
    {editing&&<div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setEditing(null)}><section className="resolution-modal" role="dialog" aria-modal="true" aria-labelledby="resolution-title">
      <header className="modal-head"><div><p className="eyebrow">Resolve {suggestionKind(editing)}</p><h2 id="resolution-title">{editing.album||editing.artist}</h2><p>{editing.artist} · {(issueCopy[editing.code]??{detail:editing.message}).detail}</p></div><button className="icon-button" onClick={()=>setEditing(null)} aria-label="Close"><X/></button></header>
      <div className="suggestion-intro"><div><strong>Best evidence-backed matches</strong><p>Curator ranks trusted catalog and artwork sources. Nothing is applied until you choose.</p></div></div>
      {original&&<section className="original-data"><strong>Your library data</strong><dl><div><dt>Artist</dt><dd>{original.artist}</dd></div><div><dt>Album</dt><dd>{original.album}</dd></div><div><dt>Date</dt><dd>{original.date}</dd></div><div><dt>Tracks</dt><dd>{original.tracks}</dd></div><div><dt>Genres</dt><dd>{original.genres.join(" · ")||"Not set"}</dd></div><div><dt>Artist MBID</dt><dd>{original.artistMbid}</dd></div><div><dt>Release-group MBID</dt><dd>{original.releaseGroupMbid}</dd></div></dl></section>}
      {loading&&<div className="loading-state"><LoaderCircle className="spin"/><span>Finding and checking candidates...</span></div>}
      {!loading&&suggestions.length>0&&<div className="suggestion-grid">{suggestions.map(suggestion=><article className="suggestion-card" key={suggestion.id}><SuggestionArtwork suggestion={suggestion}/><div className="suggestion-body"><div className="confidence-row"><span>{Math.round(suggestion.confidence*100)}% match</span><small>{suggestion.provider}</small></div><h3>{suggestion.label}</h3><p>{suggestion.evidence}</p>{suggestion.facts?.length?<ul className="suggestion-facts">{suggestion.facts.map(fact=><li key={fact}>{fact}</li>)}</ul>:null}{suggestion.sourcePage&&<a href={suggestion.sourcePage} target="_blank" rel="noreferrer">Inspect source <ExternalLink size={14}/></a>}<button className="btn-primary" disabled={Boolean(applying)} onClick={()=>void applySuggestion(suggestion)}>{applying===suggestion.id?<LoaderCircle className="spin" size={16}/>:null}Use this suggestion</button></div></article>)}</div>}
      {!loading&&!suggestions.length&&<div className="empty-state"><strong>No safe automatic match found</strong><p>Enter a catalog ID or upload verified artwork below.</p></div>}{notice&&<p className="form-notice error">{notice}</p>}
      <details className="manual-fallback"><summary><Upload size={17}/>Upload or enter manually</summary><form className="manual-form" onSubmit={applyManual}><div className="manual-grid"><label>Artist<input name="artist" defaultValue={editing.artist||""}/></label><label>Album<input name="album" defaultValue={editing.album||""}/></label><label>MusicBrainz artist ID<input name="artistMbid" placeholder="Optional UUID"/></label><label>MusicBrainz release-group ID<input name="releaseGroupMbid" placeholder="Optional UUID"/></label><label>Album cover<input name="cover" type="file" accept="image/*"/></label><label>Artist image<input name="artistImage" type="file" accept="image/*"/></label></div><button className="btn-secondary" disabled={Boolean(applying)}>{applying==="manual"?"Applying...":"Apply manual update"}</button></form></details>
    </section></div>}
  </>
}
function CoverageContext({filter,summary}:{filter:string;summary:Summary|null}){if(!summary)return null;const semantic=summary.semantic,total=semantic.complete+semantic.partial+semantic.failed+semantic.pending,percent=total?Math.round(semantic.complete/total*100):100,portablePending=Math.max(...["albumArtist","genre","style","mood","scene"].map(key=>summary.coverage[key]?.missing??0));if(filter!=="metadata"&&percent===100&&!portablePending)return null;return <section className="automation-progress"><div><span className="eyebrow">Metadata coverage</span><strong>{percent}% of tracks understood</strong><p>{semantic.pending.toLocaleString()} tracks remain in the semantic queue.</p></div><div className="automation-meter"><i style={{width:`${percent}%`}}/></div><small>{portablePending?`${portablePending} albums still have at least one portable tag gap.`:"Portable album tags are complete."}</small></section>}
function Empty({filter,summary}:{filter?:string;summary?:Summary|null}){if(filter==="metadata"){const portableMissing=summary?["genre","style","mood","scene","albumArtist"].some(key=>(summary.coverage[key]?.missing??0)>0):false,semanticPending=summary?summary.semantic.pending+summary.semantic.partial+summary.semantic.failed:0;return <div className="queue-clear"><CheckCircle2/><div><strong>Metadata is complete</strong><p>{portableMissing||semanticPending?"Another metadata category is still processing.":"Portable tags and semantic profiles are current."}</p></div></div>}if(filter==="missing-artwork"&&summary){const artist=summary.coverage.artist?.missing??0,composer=summary.coverage.composer?.missing??0;return <div className="queue-clear"><CheckCircle2/><div><strong>No artwork decisions waiting</strong><p>{artist+composer?"Automatic artwork discovery may still be running.":"Artwork review is clear."}</p></div></div>}return <div className="queue-clear"><CheckCircle2/><div><strong>Nothing needs your attention</strong><p>This queue is clear.</p></div></div>}
function SuggestionArtwork({suggestion}:{suggestion:Suggestion}){const[failed,setFailed]=useState(false);if(suggestion.imageUrl&&!failed)return <img className="suggestion-image" src={suggestion.imageUrl} alt={`${suggestion.album??suggestion.artist??"Catalog"} artwork`} onError={()=>setFailed(true)}/>;return <div className="suggestion-placeholder catalog-details"><Search/><strong>Catalog identity</strong><span>{suggestion.releaseGroupMbid||"Evidence-backed match"}</span></div>}
