"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, ExternalLink, ImageOff, LoaderCircle, Save, Upload, X } from "lucide-react";

type Track={id:number;title:string;artist:string;album:string;track:number;disc:number;year:string;path:string;status:string;tags:Record<string,unknown>;profile:Record<string,unknown>|null;profileStatus:string};
type Entity={view:string;key:string;title:string;subtitle:string;artwork:string;summary:{artist:string;album:string;year:string;genres:string[];styles:string[];moods:string[];scenes:string[];labels:string[]};tracks:Track[]};
const labels:Record<string,string>={title:"Title",artist:"Artist",album:"Album",albumArtist:"Album artist",year:"Release year",composer:"Composer",label:"Record label",genre:"Genres",style:"Styles",mood:"Moods",scene:"Scenes"};

export function LibraryEntityDrawer({view,entityKey,onClose,onSaved}:{view:string;entityKey:string;onClose:()=>void;onSaved:()=>void}){
  const [entity,setEntity]=useState<Entity|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[uploading,setUploading]=useState(false),[selected,setSelected]=useState<number|null>(null),[form,setForm]=useState<Record<string,string>>({});
  useEffect(()=>{setEntity(null);setError("");fetch(`/api/library/entity?view=${encodeURIComponent(view)}&key=${encodeURIComponent(entityKey)}`,{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Could not load item");setEntity(body);setSelected(body.tracks[0]?.id??null)}).catch(reason=>setError(String(reason)))},[view,entityKey]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);
  const track=useMemo(()=>entity?.tracks.find(item=>item.id===selected)??entity?.tracks[0],[entity,selected]);
  useEffect(()=>{if(!entity||!track)return;const tags=track.tags,one=(value:unknown)=>Array.isArray(value)?String(value[0]??""):String(value??"");setForm({title:one(tags.title)||track.title,artist:one(tags.artist)||track.artist,album:one(tags.album)||track.album,albumArtist:one(tags.albumArtist),year:one(tags.date)||track.year,genre:entity.summary.genres.join("; "),style:entity.summary.styles.join("; "),mood:entity.summary.moods.join("; "),scene:entity.summary.scenes.join("; "),composer:one(tags.composer),label:entity.summary.labels.join("; ")})},[entity,track]);
  async function save(event?:FormEvent){event?.preventDefault();if(!entity||!track)return;setSaving(true);setError("");setSaved(false);try{const albumWide=view==="albums",fileIds=albumWide?entity.tracks.map(item=>item.id):[track.id],patch=albumWide?{album:form.album,albumArtist:form.albumArtist,year:form.year,genre:form.genre,style:form.style,mood:form.mood,scene:form.scene,label:form.label}:{...form};const response=await fetch("/api/library/entity",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileIds,patch})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Save failed");setSaved(true);onSaved()}catch(reason){setError(String(reason))}finally{setSaving(false)}}
  async function upload(file:File){if(!entity?.tracks[0]?.id)return;setUploading(true);setError("");try{const data=new FormData();data.set("fileId",String(entity.tracks[0].id));data.set("kind",view==="artists"||view==="composers"?"artist":"album");data.set("image",file);const response=await fetch("/api/library/artwork",{method:"POST",body:data}),body=await response.json();if(!response.ok)throw new Error(body.error||"Artwork upload failed");setEntity({...entity,artwork:`${entity.artwork}&manual=${Date.now()}`});onSaved()}catch(reason){setError(String(reason))}finally{setUploading(false)}}
  const mainFields=view==="albums"?["album","albumArtist","year","label"]:["title","artist","album","albumArtist","year","composer","label"];
  const renderFields=(keys:string[])=>keys.map(key=><label key={key}><span>{labels[key]}</span><input value={form[key]??""} onChange={event=>setForm(current=>({...current,[key]:event.target.value}))}/></label>);
  return <div className="drawer-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="entity-drawer" role="dialog" aria-modal="true" aria-labelledby="entity-title"><button className="icon-button drawer-close" onClick={onClose} aria-label="Close editor"><X/></button>{error&&<div className="inline-error">{error}</div>}{!entity&&!error?<div className="drawer-loading"><LoaderCircle className="spin"/><span>Loading details</span></div>:entity&&<>
    <header className="entity-hero"><div className="entity-art"><img src={entity.artwork} alt="" onError={event=>{event.currentTarget.style.display="none"}}/><ImageOff className="art-fallback"/><label className="art-upload"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={event=>event.target.files?.[0]&&void upload(event.target.files[0])}/>{uploading?<LoaderCircle className="spin"/>:<Upload/>}<span>{uploading?"Preparing":"Change artwork"}</span></label></div><div><span className="kicker">{entity.view.slice(0,-1)||entity.view}</span><h2 id="entity-title">{entity.title}</h2><p>{entity.subtitle}</p><div className="tag-row">{entity.summary.genres.map(item=><span key={item}>{item}</span>)}</div></div></header>
    <div className="entity-body">{entity.tracks.length>1&&<nav className="track-rail" aria-label="Tracks"><h3>{entity.tracks.length} tracks</h3>{entity.tracks.map(item=><button key={item.id} className={item.id===track?.id?"selected":""} onClick={()=>setSelected(item.id)}><span>{item.track||"-"}</span><strong>{item.title}</strong><i>{item.status}</i></button>)}</nav>}
      <form className="metadata-editor" onSubmit={save}><div className="section-heading"><div><span className="kicker">Metadata</span><h3>{view==="albums"?"Album details":"Track details"}</h3></div><span className="write-note">Saved safely by Curator</span></div><div className="field-grid">{renderFields(mainFields)}</div><details className="classification-fields" open><summary>Classification</summary><p>Use semicolons between multiple values.</p><div className="field-grid">{renderFields(["genre","style","mood","scene"])}</div></details>{track?.profile&&<details className="profile-details"><summary>Technical profile</summary><pre>{JSON.stringify(track.profile,null,2)}</pre></details>}<div className="editor-actions"><a className="text-link" href={`http://localhost:4533/app/#/search?query=${encodeURIComponent(entity.title)}`} target="_blank"><ExternalLink/>Open in Navidrome</a><button className="primary-button" disabled={saving}>{saving?<LoaderCircle className="spin"/>:saved?<Check/>:<Save/>}{saved?"Queued":"Save changes"}</button></div></form>
    </div></>}</aside></div>;
}
