"use client";
import { useCallback,useEffect,useState } from "react";
import { AudioLines,Brain,CheckCircle2,Search,SlidersHorizontal,X } from "lucide-react";
import type { CategorizationSummary } from "@/features/categorization/query";

type Profile=Record<string,unknown>;type Row={id:number;artist:string;album:string;title:string;path:string;status:string;profile:Profile|null;manual:Profile;last_error?:string};
const arrayFields=["genre","style","mood","groove","texture","timbre","production","vocalProfile","instrumentation","languages","lyricalThemes","listeningContexts","scenes","styleEra","meter","dynamicCharacter","structuralCharacter","recordingTypes"];
const scalarFields=["valence","energy","bpm","tempoFeel","danceability","acousticElectronicCharacter","musicalKey","mode"];
const label=(value:string)=>value.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ");
const values=(profile:Profile|null,field:string)=>{const value=profile?.[field];return Array.isArray(value)?value.map(String):value==null||value===""?[]:[String(value)]};

export function SemanticCoverage({data}:{data:CategorizationSummary}){const percent=data.total?Math.round(data.complete/data.total*100):0,core=["genre","style","mood","energy","groove","texture","timbre","production","vocalProfile"];return <section className="paper semantic-coverage"><div className="section-heading"><div><p className="eyebrow">Track understanding</p><h3>Semantic categorization</h3></div><strong>{percent}% complete</strong></div><div className="semantic-summary"><span><Brain/> {data.complete.toLocaleString()} rich profiles</span><span><AudioLines/> {data.audioAnalyzed.toLocaleString()} audio analyses</span><span>{data.partial.toLocaleString()} partial</span><span>{data.pending.toLocaleString()} pending</span></div><div className="dimension-grid">{core.map(field=>{const item=data.dimensions[field],coverage=item?.total?Math.round(item.present/item.total*100):0;return <div key={field}><span>{label(field)}</span><b>{coverage}%</b><i><em style={{width:`${coverage}%`}}/></i></div>})}</div></section>}

export function SemanticLibrary(){const[rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<CategorizationSummary|null>(null),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[editing,setEditing]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const load=useCallback(async()=>{const response=await fetch(`/api/categorization/tracks?search=${encodeURIComponent(search)}&status=${status}&limit=80`,{cache:"no-store"});if(!response.ok)throw new Error(await response.text());const data=await response.json();setRows(data.rows);setSummary(data.summary)},[search,status]);useEffect(()=>{const id=setTimeout(()=>void load().catch(value=>setError(String(value))),250);return()=>clearTimeout(id)},[load]);return <section className="paper semantic-library"><div className="section-heading"><div><p className="eyebrow">Music understanding</p><h3>Track semantic profiles</h3></div>{summary&&<span className="quiet-count">{summary.complete.toLocaleString()} complete / {summary.pending.toLocaleString()} pending</span>}</div><div className="semantic-toolbar"><label><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Track, artist, album, genre, mood, or semantic tag"/></label><label><SlidersHorizontal/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All states</option><option value="complete">Complete</option><option value="partial">Sparse / partial</option><option value="failed">Failed</option><option value="pending">Pending</option></select></label></div>{error&&<p className="semantic-error">{error}</p>}<div className="semantic-rows">{rows.map(row=><button key={row.id} onClick={()=>row.profile&&setEditing(row)}><span className={`semantic-state ${row.status}`}>{row.status==="complete"?<CheckCircle2/>:<Brain/>}</span><span><strong>{row.title}</strong><small>{row.artist} / {row.album}</small><span className="tag-preview">{[...values(row.profile,"genre"),...values(row.profile,"style"),...values(row.profile,"mood")].slice(0,6).map(value=><i key={value}>{label(value)}</i>)}</span></span><em>{values(row.profile,"energy")[0]?.replaceAll("_"," ")??"not analyzed"}</em></button>)}</div>{editing&&<Editor row={editing} busy={busy} close={()=>setEditing(null)} save={async patch=>{setBusy(true);setError("");try{const response=await fetch("/api/categorization/tracks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileId:editing.id,patch})});if(!response.ok)throw new Error(await response.text());setEditing(null);await load()}catch(value){setError(String(value))}finally{setBusy(false)}}}/>}</section>}

function Editor({row,busy,close,save}:{row:Row;busy:boolean;close:()=>void;save:(patch:Profile)=>Promise<void>}){const initial=Object.fromEntries([...arrayFields,...scalarFields].map(field=>[field,values(row.profile,field).join(", ")])),[draft,setDraft]=useState<Record<string,string>>(initial);const submit=()=>{const patch:Profile={};for(const field of arrayFields)patch[field]=draft[field].split(",").map(value=>value.trim()).filter(Boolean);for(const field of scalarFields)patch[field]=field==="bpm"?(draft[field]?Number(draft[field]):null):(draft[field]||null);void save(patch)};return <div className="modal-backdrop"><section className="semantic-editor paper"><header><div><p className="eyebrow">Manual correction</p><h3>{row.title}</h3><p>{row.artist} / {row.album}</p></div><button onClick={close}><X/></button></header><p className="editor-note">Manual values have priority over later automatic classification. Separate multiple values with commas.</p><div className="editor-grid">{[...arrayFields,...scalarFields].map(field=><label key={field}><span>{label(field)}</span><input value={draft[field]} onChange={event=>setDraft({...draft,[field]:event.target.value})}/></label>)}</div><footer><button className="action-button secondary" onClick={close}>Cancel</button><button className="action-button primary" disabled={busy} onClick={submit}>{busy?"Saving":"Apply correction"}</button></footer></section></div>}
