"use client";
import { useEffect,useState } from "react";
import { Activity,Database,Download,HardDrive,Radio,Telescope,Users } from "lucide-react";
type Service={ok:boolean;data?:Record<string,unknown>;error?:string};
const definitions=[{key:"lidarr",name:"Lidarr",icon:Radio},{key:"prowlarr",name:"Prowlarr",icon:Telescope},{key:"qbittorrent",name:"qBittorrent",icon:Download},{key:"navidrome",name:"Navidrome",icon:Activity}] as const;
function detail(key:string,service:Service):string{if(!service.ok)return service.error??"Unavailable";const data=service.data??{};if(key==="lidarr")return`${Number(data.queue??0).toLocaleString()} downloads queued`;if(key==="prowlarr")return`${data.enabled??0} of ${data.total??0} indexers enabled`;if(key==="qbittorrent")return`${data.torrents??0} torrents / ${formatRate(Number(data.downloadSpeed??0))}`;return"Music server reachable"}
function formatRate(value:number):string{return value<1024?`${value} B/s`:value<1024**2?`${(value/1024).toFixed(1)} KB/s`:`${(value/1024**2).toFixed(1)} MB/s`}
function formatBytes(value:number):string{return value<1024**3?`${(value/1024**2).toFixed(1)} MB`:value<1024**4?`${(value/1024**3).toFixed(1)} GB`:`${(value/1024**4).toFixed(1)} TB`}
export function StackCards({refreshSeconds}:{refreshSeconds?:number}){const[data,setData]=useState<Record<string,Service>|null>(null),[configured,setConfigured]=useState(refreshSeconds??15);useEffect(()=>{if(refreshSeconds!==undefined){setConfigured(refreshSeconds);return}fetch("/api/settings").then(response=>response.json()).then(settings=>setConfigured(Number(settings.stackRefreshSeconds)||15)).catch(()=>{})},[refreshSeconds]);useEffect(()=>{const load=()=>fetch("/api/stack/summary").then(response=>response.json()).then(setData).catch(()=>setData({}));load();const id=setInterval(load,configured*1_000);return()=>clearInterval(id)},[configured]);const qbit=data?.qbittorrent,q=qbit?.data??{};return <><section className="service-grid">{definitions.map(({key,name,icon:Icon})=>{const service=data?.[key];return <article className="paper service-card" key={key}><Icon/><div><p className="eyebrow">{name}</p><strong>{!data?"Loading":service?.ok?"Operational":"Needs attention"}</strong><span>{!data?"Fetching independently":service?detail(key,service):"No response"}</span></div><i className={!data?"loading":service?.ok?"ok":"bad"}/></article>})}</section>{qbit&&<article className={`paper torrent-facts ${qbit.ok?"":"unavailable"}`}><header><div><Download/><span><strong>Download activity</strong><small>{qbit.ok?`${Number(q.torrents??0).toLocaleString()} managed torrents · ${String(q.connection??"unknown")} connection`:qbit.error??"qBittorrent unavailable"}</small></span></div>{qbit.ok&&<b>{formatRate(Number(q.downloadSpeed??0))}<small>down now</small></b>}</header>{qbit.ok&&<div className="torrent-fact-grid"><span><Download/><b>{Number(q.active??0).toLocaleString()}</b><small>Active</small></span><span className={Number(q.stalled)>0?"warn":""}><Activity/><b>{Number(q.stalled??0).toLocaleString()}</b><small>Stalled</small></span><span><Database/><b>{Number(q.queued??0).toLocaleString()}</b><small>Queued</small></span><span><Users/><b>{Number(q.connectedSeeds??0).toLocaleString()} / {Number(q.connectedPeers??0).toLocaleString()}</b><small>Seeds / peers</small></span><span><HardDrive/><b>{formatBytes(Number(q.remainingBytes??0))}</b><small>Remaining</small></span><span><HardDrive/><b>{formatBytes(Number(q.freeSpace??0))}</b><small>Disk free</small></span></div>}</article>}</>}
