import { execFile } from "node:child_process";
import { mkdir,readFile,rename,rm } from "node:fs/promises";
import { basename,dirname,extname } from "node:path";
import { promisify } from "node:util";
import { randomUUID } from "node:crypto";
import sharp from "sharp";
import { db } from "@/features/db/client";
import { artistWikidataId } from "@/features/sources/musicbrainz";
import { cachedJson,fetchJson } from "@/features/sources/cache";
import { discoverArtwork } from "./web-discovery";
import { config } from "@/config";
import { normalized } from "@/features/scanner/normalize";
const run=promisify(execFile);
async function existingGood(path:string,min=300):Promise<boolean>{try{const meta=await sharp(path).metadata();return(meta.width??0)>=min&&(meta.height??0)>=min}catch{return false}}
async function persistImage(path:string,bytes:ArrayBuffer|Buffer):Promise<{width:number;height:number}>{await mkdir(dirname(path),{recursive:true});const temp=`${path}.curator-${process.pid}-${randomUUID()}`;try{const info=await sharp(bytes instanceof ArrayBuffer ? Buffer.from(new Uint8Array(bytes)) : bytes).rotate().resize({width:2000,height:2000,fit:"inside",withoutEnlargement:true}).flatten({background:"#f5f0e6"}).jpeg({quality:90,mozjpeg:true}).toFile(temp);await rename(temp,path);return{width:info.width,height:info.height}}finally{await rm(temp,{force:true})}}
async function tryPersistImage(path:string,bytes:ArrayBuffer|Buffer):Promise<{width:number;height:number}|undefined>{try{return await persistImage(path,bytes)}catch{return undefined}}
function record(key:string,kind:string,path:string,provider:string,url:string,license:string,width:number,height:number):void{db().prepare("INSERT OR REPLACE INTO artwork(entity_key,kind,path,provider,source_url,license,width,height) VALUES (?,?,?,?,?,?,?,?)").run(key,kind,path,provider,url,license,width,height)}
async function embedded(key:string,target:string):Promise<boolean>{const file=db().prepare("SELECT path FROM files WHERE album_key=? AND format='flac' ORDER BY id LIMIT 1").get(key) as{path:string}|undefined;if(!file)return false;const temp=`${target}.embedded-${process.pid}`;try{await run("metaflac",[`--export-picture-to=${temp}`,file.path],{timeout:120_000});const bytes=await readFile(temp),meta=await sharp(bytes).metadata();if((meta.width??0)<300||(meta.height??0)<300)return false;const dimensions=await persistImage(target,bytes);record(key,"cover",target,"embedded",file.path,"Embedded in owned media",dimensions.width,dimensions.height);return true}catch{return false}finally{await rm(temp,{force:true})}}
export async function ensureCover(key:string,releaseGroupId:string|undefined,albumDir:string):Promise<string|undefined>{const path=`${albumDir}/cover.jpg`;if(await existingGood(path))return path;const parentCover=/^(cd|disc|disk)[ _-]*\d+$/i.test(basename(albumDir))?`${dirname(albumDir)}/cover.jpg`:undefined;if(parentCover&&await existingGood(parentCover)){const dimensions=await tryPersistImage(path,await readFile(parentCover));if(dimensions){record(key,"cover",path,"local-sidecar",parentCover,"Owned media sidecar",dimensions.width,dimensions.height);return path}}if(await embedded(key,path))return path;if(releaseGroupId){type Caa={images?:Array<{front:boolean;approved:boolean;image:string;thumbnails?:Record<string,string>}>};const response=await fetch(`https://coverartarchive.org/release-group/${releaseGroupId}`,{signal:AbortSignal.timeout(20_000)}).catch(()=>undefined);if(response?.ok){const data=await response.json() as Caa,candidate=data.images?.find(image=>image.front&&image.approved)??data.images?.find(image=>image.front),url=candidate?.thumbnails?.["1200"]??candidate?.image;if(url){const image=await fetch(url,{signal:AbortSignal.timeout(30_000)}).catch(()=>undefined);if(image?.ok){const dimensions=await tryPersistImage(path,await image.arrayBuffer());if(dimensions){record(key,"cover",path,"cover-art-archive",url,"Cover Art Archive",dimensions.width,dimensions.height);return path}}}}}
  const row=db().prepare("SELECT artist_name,album_name,tags_json FROM files WHERE album_key=? LIMIT 1").get(key) as{artist_name:string;album_name:string;tags_json:string}|undefined,tags=row?JSON.parse(row.tags_json) as Record<string,unknown>:{};const year=String(tags.year??tags.date??"").slice(0,4),found=row?await discoverArtwork(key,"cover",row.artist_name,row.album_name,year,releaseGroupId):undefined;if(found){const dimensions=await tryPersistImage(path,found.bytes);if(dimensions){record(key,"cover",path,"local-ai-web",found.sourcePage,"unknown-personal-use",dimensions.width,dimensions.height);return path}}return undefined}
export function centralArtistPath(name:string):string|undefined{const safe=name.trim().replaceAll("/","_");return!safe||safe==="."||safe===".."||/\0/.test(safe)?undefined:`${config.MUSIC_ROOT}/.artist-images/${safe}.jpg`}
async function deezerArtist(entityKey:string,artistName:string,target:string):Promise<string|undefined>{type Result={data?:Array<{name?:string;picture_xl?:string;picture_big?:string;rank?:number}>};const key=normalized(artistName),result=await cachedJson("deezer",`artist-search:${key}`,entityKey,30,()=>fetchJson<Result>(`https://api.deezer.com/search/artist?limit=10&q=${encodeURIComponent(artistName)}`)).catch(()=>undefined),candidate=result?.data?.filter(item=>item.name&&normalized(item.name)===key&&(item.picture_xl||item.picture_big)).sort((a,b)=>(b.rank??0)-(a.rank??0))[0],url=candidate?.picture_xl??candidate?.picture_big;if(!url)return undefined;const response=await fetch(url,{signal:AbortSignal.timeout(20_000)}).catch(()=>undefined);if(!response?.ok)return undefined;const dimensions=await tryPersistImage(target,await response.arrayBuffer());if(!dimensions)return undefined;record(entityKey,"artist",target,"deezer",url,"unknown-personal-use",dimensions.width,dimensions.height);return target}
export async function ensureNamedArtistImage(options:{entityKey:string;artistName:string;artistId?:string;target:string;seedPaths?:string[];context?:string;allowWeb?:boolean}):Promise<string|undefined>{const{entityKey,artistName,artistId,target,seedPaths=[],context,allowWeb=true}=options;if(await existingGood(target))return target;for(const seed of seedPaths)if(seed!==target&&await existingGood(seed)){const dimensions=await tryPersistImage(target,await readFile(seed));if(dimensions){record(entityKey,"artist",target,"local-sidecar",seed,"Owned media sidecar",dimensions.width,dimensions.height);return target}}
  if(artistId){const wikidata=await artistWikidataId(artistId,entityKey).catch(()=>undefined);if(wikidata){type Entity={entities:Record<string,{claims?:{P18?:Array<{mainsnak?:{datavalue?:{value?:string}}}>}}>};const entity=await fetchJson<Entity>(`https://www.wikidata.org/wiki/Special:EntityData/${wikidata}.json`).catch(()=>undefined),filename=entity?.entities[wikidata]?.claims?.P18?.[0]?.mainsnak?.datavalue?.value;if(filename){const url=`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(filename)}?width=2000`,response=await fetch(url,{signal:AbortSignal.timeout(30_000)}).catch(()=>undefined);if(response?.ok){const dimensions=await tryPersistImage(target,await response.arrayBuffer());if(dimensions){record(entityKey,"artist",target,"wikimedia",url,"See source",dimensions.width,dimensions.height);return target}}}}}
  const deezer=await deezerArtist(entityKey,artistName,target);if(deezer)return deezer;if(!allowWeb)return undefined;const found=await discoverArtwork(entityKey,"artist",artistName,undefined,undefined,artistId,context);if(!found)return undefined;const dimensions=await tryPersistImage(target,found.bytes);if(!dimensions)return undefined;record(entityKey,"artist",target,"local-ai-web",found.sourcePage,"unknown-personal-use",dimensions.width,dimensions.height);return target}
export async function ensureArtistMbidAlias(artistId:string,source:string):Promise<void>{const alias=`${config.MUSIC_ROOT}/.artist-images/${artistId}.jpg`;if(await existingGood(alias))return;const dimensions=await tryPersistImage(alias,await readFile(source));if(dimensions)record(`artist:${artistId}`,"artist",alias,"central-artist-image",source,"Owned media sidecar",dimensions.width,dimensions.height)}
export async function ensureArtistImage(key:string,artistId:string|undefined,artistDir:string):Promise<void>{const row=db().prepare("SELECT artist_name FROM files WHERE album_key=? LIMIT 1").get(key) as{artist_name:string}|undefined;if(!row)return;const local=`${artistDir}/artist.jpg`,central=centralArtistPath(row.artist_name),entityKey=`artist:${artistId??row.artist_name}`,target=central??local,found=await ensureNamedArtistImage({entityKey,artistName:row.artist_name,artistId,target,seedPaths:[local]});if(found&&found!==local&&!await existingGood(local)){const dimensions=await tryPersistImage(local,await readFile(found));if(dimensions)record(entityKey,"artist",local,"central-artist-image",found,"Owned media sidecar",dimensions.width,dimensions.height)}if(found&&artistId)await ensureArtistMbidAlias(artistId,found)}
