import { lookup } from "node:dns/promises";
import OpenAI from "openai";
import sharp from "sharp";
import { config,versions } from "@/config";
import { db } from "@/features/db/client";
import { normalized } from "@/features/scanner/normalize";
const client=new OpenAI({apiKey:config.OPENAI_API_KEY||"missing"});
type Candidate={sourcePage:string;imageUrl:string;confidence:number;evidence:string};
const schema={type:"object",additionalProperties:false,required:["candidates"],properties:{candidates:{type:"array",maxItems:5,items:{type:"object",additionalProperties:false,required:["sourcePage","imageUrl","confidence","evidence"],properties:{sourcePage:{type:"string"},imageUrl:{type:"string"},confidence:{type:"number",minimum:0,maximum:1},evidence:{type:"string"}}}}}} as const;
function privateAddress(address:string):boolean{return address==="::1"||address.startsWith("fe80:")||address.startsWith("fc")||address.startsWith("fd")||/^10\.|^127\.|^169\.254\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(address)}
async function safeUrl(value:string):Promise<URL>{const url=new URL(value);if(url.protocol!=="https:")throw new Error("Only HTTPS artwork sources are allowed");const addresses=await lookup(url.hostname,{all:true});if(!addresses.length||addresses.some(item=>privateAddress(item.address)))throw new Error("Private artwork destination rejected");return url}
async function safeFetch(value:string,accept:string,max:number):Promise<{response:Response,url:URL,bytes:Buffer}>{let url=await safeUrl(value);for(let hop=0;hop<4;hop++){const response=await fetch(url,{redirect:"manual",signal:AbortSignal.timeout(20_000),headers:{Accept:accept,"User-Agent":"MusicCurator/2.0"}});if(response.status>=300&&response.status<400){const next=response.headers.get("location");if(!next)throw new Error("Invalid artwork redirect");url=await safeUrl(new URL(next,url).toString());continue}if(!response.ok)throw new Error(`${response.status} ${url}`);const length=Number(response.headers.get("content-length")??0);if(length>max)throw new Error("Artwork response too large");const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>max)throw new Error("Artwork response too large");return{response,url,bytes}}throw new Error("Too many artwork redirects")}
function metaImage(html:string,base:URL):string|undefined{const patterns=[/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image/i,/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)/i,/<link[^>]+rel=["']image_src["'][^>]+href=["']([^"']+)/i];for(const pattern of patterns){const found=html.match(pattern)?.[1];if(found)return new URL(found.replaceAll("&amp;","&"),base).toString()}}
async function inspect(candidate:Candidate,artist:string,album:string|undefined):Promise<{bytes:Buffer;sourcePage:string;imageUrl:string;confidence:number}>{const page=await safeFetch(candidate.sourcePage,"text/html",2*1024*1024),html=page.bytes.toString("utf8"),plain=normalized(html.replace(/<[^>]+>/g," "));if(!plain.includes(normalized(artist)))throw new Error("Source page does not identify the artist");if(album&&!plain.includes(normalized(album)))throw new Error("Source page does not identify the album");const imageUrl=candidate.imageUrl||metaImage(html,page.url);if(!imageUrl)throw new Error("Source page has no declared image");const image=await safeFetch(imageUrl,"image/*",20*1024*1024),type=image.response.headers.get("content-type")??"";if(!type.startsWith("image/"))throw new Error("Candidate is not an image");const metadata=await sharp(image.bytes).metadata();if((metadata.width??0)<800||(metadata.height??0)<800)throw new Error("Candidate image is below 800px");return{bytes:image.bytes,sourcePage:page.url.toString(),imageUrl:image.url.toString(),confidence:candidate.confidence}}
async function search(model:string,artist:string,album:string|undefined,year:string|undefined,mbid:string|undefined,context:string|undefined):Promise<Candidate[]>{const subject=album?`album cover for ${artist} - ${album}`:`artist photograph for ${artist}`;const effort=model===config.OPENAI_LUNA_MODEL?"low":model===config.OPENAI_TERRA_MODEL?"medium":"high";const response=await client.responses.create({model,reasoning:{effort},tools:[{type:"web_search"}],input:`Find publicly accessible high-resolution ${subject}. Use official artist/label pages, Bandcamp, Discogs, Wikimedia, Internet Archive, retailer pages, and authoritative discography pages. Ignore rip labels and edition annotations when they do not change the canonical cover. Identity evidence: year=${year??"unknown"}, MusicBrainz ID=${mbid??"unknown"}, context=${context??"none"}. Return source pages and direct image URL when visible. Never suggest generated artwork or an image for a different person, artist, release, or edition.`,text:{format:{type:"json_schema",name:"artwork_candidates",strict:true,schema}}},{timeout:90_000,maxRetries:0});return(JSON.parse(response.output_text) as{candidates:Candidate[]}).candidates}
export async function discoverArtwork(entityKey:string,kind:"cover"|"artist",artist:string,album?:string,year?:string,mbid?:string,context?:string):Promise<{bytes:Buffer;sourcePage:string;imageUrl:string;confidence:number}|undefined>{if(!config.OPENAI_API_KEY)return undefined;const attempts=(db().prepare("SELECT count(*) count FROM artwork_attempts WHERE entity_key=? AND kind=? AND provider='openai-web' AND policy_version=?").get(entityKey,kind,versions.artwork) as{count:number}).count;if(attempts>=2)return undefined;const models=[config.OPENAI_LUNA_MODEL,config.OPENAI_TERRA_MODEL,config.OPENAI_SOL_MODEL];for(const model of models){try{const candidates=(await search(model,artist,album,year,mbid,context)).sort((a,b)=>b.confidence-a.confidence);for(const candidate of candidates){if(candidate.confidence<.92)continue;try{const found=await inspect(candidate,artist,album);db().prepare("INSERT INTO artwork_attempts(entity_key,kind,provider,status,source_page,message,confidence,policy_version) VALUES (?,?,'openai-web','accepted',?,?,?,?)").run(entityKey,kind,found.sourcePage,candidate.evidence,found.confidence,versions.artwork);return found}catch(error){db().prepare("INSERT INTO artwork_attempts(entity_key,kind,provider,status,source_page,message,confidence,policy_version) VALUES (?,?,'openai-web','rejected',?,?,?,?)").run(entityKey,kind,candidate.sourcePage,String(error),candidate.confidence,versions.artwork)}}}catch(error){db().prepare("INSERT INTO artwork_attempts(entity_key,kind,provider,status,message,policy_version) VALUES (?,?,'openai-web','failed',?,?)").run(entityKey,kind,String(error),versions.artwork)}}return undefined}
