import { mkdir,writeFile } from "node:fs/promises";
import { enrichmentJsonSchema,enrichmentSchema } from "../src/features/contracts/schema";
import type { EnrichmentDecision,EvidenceFact } from "../src/features/contracts/types";
import { enrichmentPrompt } from "../src/features/enrichment/prompts";
import { categorizationInstructions,classificationPayload } from "../src/features/categorization/classify";
import { semanticBatchJsonSchema,semanticBatchSchema } from "../src/features/categorization/schema";
import type { TrackClassificationInput,TrackSemanticProfile } from "../src/features/categorization/types";
import { normalizeProfile } from "../src/features/categorization/vocabulary";
import { CuratorAiClient,type AiResult,type ReasoningEffort } from "../src/features/ai/client";
import { playlistDiscoveryJsonSchema,playlistDiscoveryOutputSchema } from "../src/features/playlists/discovery";

type ModelTarget={id:string;model:string;effort:ReasoningEffort;client:CuratorAiClient};
type Check={name:string;passed:boolean;detail?:string};
type Run={caseId:string;target:string;model:string;durationMs:number;usage?:AiResult<unknown>["usage"];valid:boolean;score:number;checks:Check[];output?:unknown;error?:string;sourceUrls?:string[]};
const openaiKey=process.env.OPENAI_API_KEY??"",localKey=process.env.LOCAL_AI_API_KEY??"";
if(!openaiKey||!localKey)throw new Error("OPENAI_API_KEY and LOCAL_AI_API_KEY are required");
const openai=new CuratorAiClient({apiKey:openaiKey,style:"responses"}),local=new CuratorAiClient({apiKey:localKey,baseURL:process.env.LOCAL_AI_BASE_URL??"https://inference.blizzard.busykoala.io/v1",style:"chat"});
const allTargets:ModelTarget[]=[
  {id:"luna",model:process.env.OPENAI_LUNA_MODEL??"gpt-5.6-luna",effort:"low",client:openai},
  {id:"terra",model:process.env.OPENAI_TERRA_MODEL??"gpt-5.6-terra",effort:"medium",client:openai},
  {id:"sol",model:process.env.OPENAI_SOL_MODEL??"gpt-5.6-sol",effort:"high",client:openai},
  {id:"local",model:process.env.LOCAL_AI_MODEL??"curator",effort:"high",client:local},
];
const requestedTargets=new Set((process.env.AI_EVAL_TARGETS??allTargets.map((target)=>target.id).join(",")).split(",").map((value)=>value.trim()).filter(Boolean));
const targets=allTargets.filter((target)=>requestedTargets.has(target.id));
if(!targets.length)throw new Error(`AI_EVAL_TARGETS did not match any target: ${[...requestedTargets].join(", ")}`);
const requestedSuites=new Set((process.env.AI_EVAL_SUITES??"enrichment,categorization,playlist,artwork").split(",").map((value)=>value.trim()).filter(Boolean));
const now="2026-09-04T20:00:00.000Z",norm=(value:string)=>value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const hit=(values:string[],patterns:string[])=>patterns.some((pattern)=>values.some((value)=>new RegExp(pattern,"i").test(norm(value))));
const fact=(provider:string,value:unknown):EvidenceFact=>({provider,sourceId:`eval:${provider}`,retrievedAt:now,value});
const taxonomy={
  genre:["African","Alternative","Ambient","Classical","Country","East/Southeast Asian","Electronic","Hip-Hop","Jazz","Latin","Metal","Pop","R&B","Reggae","Rock","South Asian","World"],
  style:["Afrobeat","Avant-Garde Jazz","Baroque","Conscious Hip-Hop","Country Pop","Dark Ambient","Desert Blues","Doom Metal","Drone","Experimental Pop","Flamenco","Highlife","Hindustani Classical","IDM","Jazz Fusion","Jazz Rap","Jazz-Rock","Latin Pop","Modal Jazz","Nashville Country","Raga","Reggaeton","Roots Reggae","Stoner Rock","Synthpop","Technopop","Tuareg Rock"],
  mood:["Aggressive","Dark","Dreamy","Eerie","Hypnotic","Introspective","Meditative","Playful","Reflective","Sensual","Tense","Triumphant","Warm"],
  scene:["British Ambient","British Heavy Metal","Cape Verde","Jamaican Roots","Japanese Technopop","Lagos Afrobeat","Nashville Country","Nigerien Tuareg","North Indian Classical","Spanish Experimental Pop","US Electric Jazz","West Coast Hip-Hop"],
};
type EnrichmentCase={id:string;artist:string;album:string;evidence:EvidenceFact[];genre:string[];style:string[];scene?:string[];forbiddenGenre?:string[]};
const enrichmentCases:EnrichmentCase[]=[
  {id:"jazz-fusion",artist:"Miles Davis",album:"Bitches Brew",evidence:[fact("musicbrainz",{date:"1970",genres:["jazz fusion","avant-garde jazz","jazz-rock"],tags:["electric jazz","psychedelic"]}),fact("discogs",{year:1970,genres:["Jazz"],styles:["Fusion","Jazz-Rock","Avant-garde Jazz"]}),fact("wikidata",{description:"1970 studio album by American jazz trumpeter Miles Davis"})],genre:["jazz"],style:["fusion","jazz rock","avant garde jazz"],scene:["electric jazz","fusion","us jazz"],forbiddenGenre:["pop","classical"]},
  {id:"baroque-classical",artist:"Johann Sebastian Bach / Glenn Gould",album:"Goldberg Variations (1955 recording)",evidence:[fact("musicbrainz",{date:"1956",genres:["classical","baroque"],tags:["keyboard","piano","variations"]}),fact("discogs",{year:1956,genres:["Classical"],styles:["Baroque"],credits:["Glenn Gould - piano"]})],genre:["classical"],style:["baroque"],forbiddenGenre:["jazz","pop"]},
  {id:"afrobeat",artist:"Fela Kuti",album:"Expensive Shit",evidence:[fact("musicbrainz",{date:"1975",genres:["afrobeat","highlife","funk"]}),fact("discogs",{country:"Nigeria",year:1975,genres:["Jazz","Funk / Soul"],styles:["Afrobeat"]}),fact("wikidata",{description:"1975 album by Nigerian Afrobeat musician Fela Kuti",place:"Lagos"})],genre:["african","world"],style:["afrobeat","highlife","funk"],scene:["lagos","niger","west african","afrobeat"],forbiddenGenre:["latin"]},
  {id:"ambient-electronic",artist:"Aphex Twin",album:"Selected Ambient Works Volume II",evidence:[fact("musicbrainz",{date:"1994",genres:["ambient","dark ambient","electronic"],tags:["drone","experimental"]}),fact("discogs",{country:"UK",year:1994,genres:["Electronic"],styles:["Ambient","Experimental"]})],genre:["ambient","electronic"],style:["dark ambient","drone","experimental"],scene:["british","uk ambient","electronic"],forbiddenGenre:["techno"]},
  {id:"latin-experimental-pop",artist:"Rosalía",album:"Motomami",evidence:[fact("musicbrainz",{date:"2022",genres:["latin pop","experimental pop","reggaeton","flamenco"]}),fact("storefront",{localizedGenre:"América latina",genres:["Pop Latino"],language:"Spanish"}),fact("wikidata",{description:"2022 album by Spanish singer Rosalía",place:"Spain"})],genre:["latin","pop"],style:["latin pop","experimental pop","reggaeton","flamenco"],scene:["spanish","latin","barcelona"],forbiddenGenre:["america latina"]},
  {id:"tuareg-desert-rock",artist:"Mdou Moctar",album:"Afrique Victime",evidence:[fact("musicbrainz",{date:"2021",genres:["desert blues","Tuareg rock","African rock"]}),fact("discogs",{country:"US",year:2021,genres:["Rock","Blues"],styles:["African","Psychedelic Rock"]}),fact("wikidata",{description:"album by Nigerien Tuareg guitarist Mdou Moctar",origin:"Agadez, Niger"})],genre:["rock","african","world"],style:["desert blues","tuareg rock","psychedelic rock"],scene:["tuareg","sahara","niger","agadez"],forbiddenGenre:["latin"]},
  {id:"conscious-jazz-rap",artist:"Kendrick Lamar",album:"To Pimp a Butterfly",evidence:[fact("musicbrainz",{date:"2015",genres:["hip hop","jazz rap","conscious hip hop"],tags:["funk","spoken word"]}),fact("discogs",{country:"US",year:2015,genres:["Hip Hop","Jazz","Funk / Soul"],styles:["Conscious","Jazz Rap"]}),fact("wikidata",{description:"2015 studio album by American rapper Kendrick Lamar",origin:"Compton, California"})],genre:["hip hop"],style:["jazz rap","conscious hip hop"],scene:["west coast","compton","california hip hop"],forbiddenGenre:["country"]},
  {id:"nashville-country",artist:"Dolly Parton",album:"Jolene",evidence:[fact("musicbrainz",{date:"1974",genres:["country","country pop"],tags:["Nashville sound"]}),fact("discogs",{country:"US",year:1974,genres:["Folk, World, & Country"],styles:["Country"]}),fact("wikidata",{description:"1974 studio album by American country singer Dolly Parton",place:"Nashville, Tennessee"})],genre:["country"],style:["country pop","nashville country"],scene:["nashville","tennessee country"],forbiddenGenre:["hip hop"]},
  {id:"jamaican-roots-reggae",artist:"Bob Marley and the Wailers",album:"Exodus",evidence:[fact("musicbrainz",{date:"1977",genres:["reggae","roots reggae"],tags:["Jamaican"]}),fact("discogs",{country:"Jamaica",year:1977,genres:["Reggae"],styles:["Roots Reggae"]}),fact("wikidata",{description:"1977 studio album by Jamaican reggae band Bob Marley and the Wailers"})],genre:["reggae"],style:["roots reggae"],scene:["jamaican","roots"],forbiddenGenre:["latin"]},
  {id:"hindustani-classical",artist:"Ravi Shankar",album:"Three Ragas",evidence:[fact("musicbrainz",{date:"1956",genres:["Indian classical","Hindustani classical"],tags:["raga","sitar"]}),fact("discogs",{country:"US",year:1956,genres:["Folk, World, & Country"],styles:["Indian Classical","Hindustani"]}),fact("wikidata",{description:"album by Indian sitarist Ravi Shankar"})],genre:["south asian","classical","world"],style:["hindustani classical","raga"],scene:["north indian","hindustani"],forbiddenGenre:["east southeast asian"]},
  {id:"japanese-technopop",artist:"Yellow Magic Orchestra",album:"Solid State Survivor",evidence:[fact("musicbrainz",{date:"1979",genres:["electronic","synthpop","technopop"]}),fact("discogs",{country:"Japan",year:1979,genres:["Electronic"],styles:["Synth-pop","Electro"]}),fact("wikidata",{description:"1979 album by Japanese electronic music band Yellow Magic Orchestra"})],genre:["electronic","east southeast asian"],style:["synthpop","technopop"],scene:["japanese","tokyo technopop"],forbiddenGenre:["south asian"]},
  {id:"doom-metal",artist:"Black Sabbath",album:"Master of Reality",evidence:[fact("musicbrainz",{date:"1971",genres:["heavy metal","doom metal"],tags:["stoner rock"]}),fact("discogs",{country:"UK",year:1971,genres:["Rock"],styles:["Heavy Metal","Doom Metal"]}),fact("wikidata",{description:"1971 studio album by English rock band Black Sabbath",origin:"Birmingham, England"})],genre:["metal","rock"],style:["doom metal","stoner rock"],scene:["british heavy metal","birmingham metal"],forbiddenGenre:["pop"]},
];
const requestedCases=new Set((process.env.AI_EVAL_CASES??enrichmentCases.map((item)=>item.id).join(",")).split(",").map((value)=>value.trim()).filter(Boolean));
const selectedEnrichmentCases=enrichmentCases.filter((item)=>requestedCases.has(item.id));

function enrichmentChecks(value:EnrichmentDecision,item:EnrichmentCase):Check[]{const all=[...value.genres,...value.styles,...value.scenes];return[
  {name:"expected broad genre",passed:hit(value.genres,item.genre),detail:value.genres.join(", ")},
  {name:"differentiating style",passed:hit(value.styles,item.style),detail:value.styles.join(", ")},
  {name:"defensible scene",passed:!item.scene||hit(value.scenes,item.scene),detail:value.scenes.join(", ")},
  {name:"no forbidden genre",passed:!item.forbiddenGenre||!hit(value.genres,item.forbiddenGenre),detail:value.genres.join(", ")},
  {name:"semantic field limits",passed:value.genres.length<=2&&value.styles.length<=3&&value.moods.length<=3&&value.scenes.length<=2},
  {name:"description limits",passed:value.artistDescription.split(/\s+/).filter(Boolean).length<=60&&value.albumDescription.split(/\s+/).filter(Boolean).length<=50},
  {name:"nonempty mood",passed:value.moods.length>0,detail:value.moods.join(", ")},
  {name:"no localized taxonomy leakage",passed:!all.some((term)=>/am[eé]rica latina|musiques du monde|alternatif et ind[eé]/i.test(term))},
]}
const weightedScore=(checks:Check[])=>Math.round(checks.filter((item)=>item.passed).length/checks.length*100)/10;

function track(id:number,artist:string,album:string,title:string,tags:Record<string,unknown>,audio:Partial<TrackClassificationInput["audio"]>):TrackClassificationInput{return{file:{id,path:`/music/${artist}/${album}/${String(id).padStart(2,"0")} ${title}.flac`,albumKey:`eval:${album}`,artist,album,format:"flac",inode:id,size:50_000_000,mtimeMs:1,sourceUpdatedAt:now,tags:{title,artist,album,...tags}},audio:{analyzedSeconds:180,sampleRate:44100,rmsDb:-14,peakDb:-1,dynamicRangeDb:10,zeroCrossingRate:.08,highFrequencyRatio:.14,estimatedBpm:120,tempoCandidates:[120],beatRegularity:.75,energy:.65,danceability:.5,...audio},sourceFingerprint:`eval-${id}`}}
const tracks=[
  track(1,"Miles Davis","Bitches Brew","Pharaoh's Dance",{date:"1970",genre:["Jazz"],style:["Jazz Fusion","Avant-Garde Jazz"],comment:"Long-form electric ensemble improvisation",bpm:"125"},{estimatedBpm:125,tempoCandidates:[62.5,125],beatRegularity:.52,energy:.62,danceability:.35,dynamicRangeDb:14}),
  track(2,"Burial","Untrue","Archangel",{date:"2007",genre:["Electronic"],style:["UK Garage","Future Garage","Dubstep"],comment:"Chopped and pitch-shifted vocal samples",bpm:"134"},{estimatedBpm:134,tempoCandidates:[67,134],beatRegularity:.78,energy:.48,danceability:.68,rmsDb:-12}),
  track(3,"Cesária Évora","Miss Perfumado","Sodade",{date:"1992",genre:["World","Folk"],style:["Morna"],language:"Cape Verdean Creole",comment:"Acoustic Cape Verdean song"},{estimatedBpm:92,tempoCandidates:[46,92],beatRegularity:.7,energy:.3,danceability:.32,dynamicRangeDb:13,highFrequencyRatio:.08}),
  track(4,"Meshuggah","obZen","Bleed",{date:"2008",genre:["Metal"],style:["Progressive Metal","Djent"],comment:"Polymetric guitar and kick-drum pattern",bpm:"115"},{estimatedBpm:115,tempoCandidates:[115,230],beatRegularity:.9,energy:.96,danceability:.22,rmsDb:-7,dynamicRangeDb:5,zeroCrossingRate:.16}),
];
const trackExpected=new Map<number,{genre:string[];style:string[];bpm:number;vocal:string[];scene:string[];language:string[];character:string[];meter?:string[]}>([
  [1,{genre:["jazz"],style:["fusion","avant garde"],bpm:125,vocal:["instrumental"],scene:["jazz","electric"],language:[],character:["acoustic electronic hybrid"]}],
  [2,{genre:["electronic"],style:["uk garage","future garage","dubstep"],bpm:134,vocal:["processed","sparse vocals"],scene:["uk","british","bass","london"],language:["english"],character:["fully electronic","mostly electronic"],meter:["4 4","common time"]}],
  [3,{genre:["folk acoustic","world"],style:["morna"],bpm:92,vocal:["clean sung","intimate","soft"],scene:["cape verde","lusophone"],language:["cape verdean creole","kriolu"],character:["fully acoustic","mostly acoustic"],meter:["4 4","common time"]}],
  [4,{genre:["metal"],style:["progressive metal","djent"],bpm:115,vocal:["growled","screamed","powerful"],scene:["swedish","progressive metal","djent"],language:["english"],character:["mostly acoustic","acoustic electronic hybrid"],meter:["4 4","common time","polymeter","mixed meter"]}],
]);
function trackChecks(value:TrackSemanticProfile,id:number):Check[]{const expected=trackExpected.get(id)!;const serialized=JSON.stringify(value);return[
  {name:"expected genre",passed:hit(value.genre,expected.genre),detail:value.genre.join(", ")},
  {name:"expected style",passed:hit(value.style,expected.style),detail:value.style.join(", ")},
  {name:"tempo interpretation",passed:value.bpm!==null&&Math.abs(value.bpm-expected.bpm)<=4,detail:String(value.bpm)},
  {name:"vocal treatment",passed:hit(value.vocalProfile,expected.vocal),detail:value.vocalProfile.join(", ")},
  {name:"scene",passed:hit(value.scenes,expected.scene),detail:value.scenes.join(", ")},
  {name:"factual language",passed:expected.language.length?hit(value.languages,expected.language):value.languages.length===0,detail:value.languages.join(", ")},
  {name:"sound-source character",passed:hit([value.acousticElectronicCharacter],expected.character),detail:value.acousticElectronicCharacter},
  {name:"defensible meter",passed:!expected.meter||hit(value.meter,expected.meter),detail:value.meter.join(", ")},
  {name:"core dimensions populated",passed:[value.mood,value.groove,value.texture,value.timbre,value.production].every((field)=>field.length>0)},
  {name:"no sensitive performer inference",passed:!/(^|[_ "'])(male|female|man|woman)([_ "']|$)/i.test(serialized)},
  {name:"no playlist role leakage",passed:!/(opener|closer|builder|playlist_peak)/i.test(serialized)},
]}

const artworkSchema={type:"object",additionalProperties:false,required:["candidates"],properties:{candidates:{type:"array",maxItems:5,items:{type:"object",additionalProperties:false,required:["sourcePage","imageUrl","confidence","evidence"],properties:{sourcePage:{type:"string"},imageUrl:{type:"string"},confidence:{type:"number",minimum:0,maximum:1},evidence:{type:"string"}}}}}};
async function reachable(value:string,expectImage=false):Promise<boolean>{try{const response=await fetch(value,{redirect:"follow",signal:AbortSignal.timeout(15_000),headers:{"User-Agent":"MusicCuratorEval/1.0"}});return response.ok&&(!expectImage||(response.headers.get("content-type")??"").startsWith("image/"))}catch{return false}}

async function main(){const runs:Run[]=[];
  if(requestedSuites.has("enrichment"))for(const item of selectedEnrichmentCases)for(const target of targets){console.log(`enrichment ${item.id} ${target.id}`);const started=Date.now();try{const response=await target.client.structured<unknown>({model:target.model,effort:target.effort,input:enrichmentPrompt(item.artist,item.album,item.evidence,taxonomy),schemaName:"music_enrichment",schema:enrichmentJsonSchema,maxOutputTokens:2_000}),output=enrichmentSchema.parse(response.data),checks=enrichmentChecks(output,item);runs.push({caseId:`enrichment:${item.id}`,target:target.id,model:target.model,durationMs:Date.now()-started,usage:response.usage,valid:true,score:weightedScore(checks),checks,output})}catch(error){runs.push({caseId:`enrichment:${item.id}`,target:target.id,model:target.model,durationMs:Date.now()-started,valid:false,score:0,checks:[],error:String(error)})}}
  const albumEvidence={artist:"Various evaluation artists",purpose:"Preserve track-level differences",sources:["embedded tags","audio analysis"]};
  if(requestedSuites.has("categorization"))for(const target of targets){console.log(`categorization batch ${target.id}`);const started=Date.now();try{const response=await target.client.structured<unknown>({model:target.model,effort:target.effort,instructions:categorizationInstructions,input:JSON.stringify({albumEvidence,tracks:tracks.map(classificationPayload)}),schemaName:"track_semantic_profiles",schema:semanticBatchJsonSchema,maxOutputTokens:8_000}),output=semanticBatchSchema.parse(response.data);let accountBatch=true;for(const item of output.tracks){const profile=normalizeProfile(item.profile),checks=trackChecks(profile,item.fileId);runs.push({caseId:`categorization:${item.fileId}`,target:target.id,model:target.model,durationMs:accountBatch?Date.now()-started:0,usage:accountBatch?response.usage:undefined,valid:true,score:weightedScore(checks),checks,output:profile});accountBatch=false}for(const item of tracks)if(!output.tracks.some((value)=>value.fileId===item.file.id))runs.push({caseId:`categorization:${item.file.id}`,target:target.id,model:target.model,durationMs:0,valid:false,score:0,checks:[],error:"Track missing from response"})}catch(error){let accountBatch=true;for(const item of tracks){runs.push({caseId:`categorization:${item.file.id}`,target:target.id,model:target.model,durationMs:accountBatch?Date.now()-started:0,valid:false,score:0,checks:[],error:String(error)});accountBatch=false}}}
  const playlistInput=`Find one or two editorially supported music releases released between 2026-05-07 and 2026-09-04 for each supplied lane. Use exact lane names. Favor reputable criticism and labels; reject charts, sponsorship, and unsupported claims. LANES=${JSON.stringify([{name:"Forward electronic",category:"discovery",intent:"Adventurous, detailed electronic music with strong sound design; not generic festival EDM",tasteLanes:["IDM","ambient techno","leftfield bass"],genres:["Electronic","Ambient"],sourceDomains:["pitchfork.com","residentadvisor.net","bandcamp.com","boomkat.com"]}])}`;
  if(requestedSuites.has("playlist"))for(const target of targets.filter((item)=>item.id==="sol"||item.id==="local")){console.log(`playlist web ${target.id}`);const started=Date.now();try{const response=await target.client.structured<unknown>({model:target.model,effort:"low",web:true,maxOutputTokens:2_000,input:playlistInput,schemaName:"playlist_discovery",schema:playlistDiscoveryJsonSchema}),output=playlistDiscoveryOutputSchema.parse(response.data),sourceChecks=await Promise.all(output.candidates.flatMap((item)=>item.sources.map((source)=>reachable(source)))),dates=output.candidates.map((item)=>Date.parse(item.releaseDate)).filter(Number.isFinite),checks:Check[]=[{name:"one or two candidates",passed:output.candidates.length>=1&&output.candidates.length<=2},{name:"exact lane",passed:output.candidates.every((item)=>item.lane==="Forward electronic")},{name:"within requested date window",passed:dates.length===output.candidates.length&&dates.every((date)=>date>=Date.parse("2026-05-07")&&date<=Date.parse("2026-09-04T23:59:59Z"))},{name:"reachable editorial sources",passed:sourceChecks.length>0&&sourceChecks.every(Boolean)},{name:"tool-grounded local URLs",passed:!response.sourceUrls||output.candidates.every((item)=>item.sources.every((source)=>response.sourceUrls!.has(source)))}];runs.push({caseId:"web:playlist-discovery",target:target.id,model:target.model,durationMs:Date.now()-started,usage:response.usage,valid:true,score:weightedScore(checks),checks,output,sourceUrls:response.sourceUrls?[...response.sourceUrls]:undefined})}catch(error){runs.push({caseId:"web:playlist-discovery",target:target.id,model:target.model,durationMs:Date.now()-started,valid:false,score:0,checks:[],error:String(error)})}}
  const artworkTargets=targets.filter((item)=>["luna","terra","local"].includes(item.id)),artworkInput="Find publicly accessible high-resolution album cover artwork for Beverly Glenn-Copeland - Keyboard Fantasies (1986). Prefer official artist/label pages, Bandcamp, Discogs, Wikimedia, Internet Archive, retailer pages, and authoritative discography pages. Return source pages and direct image URLs actually visible in sources. Never suggest generated artwork or a different edition's unrelated image.";
  if(requestedSuites.has("artwork"))for(const target of artworkTargets){console.log(`artwork web ${target.id}`);const started=Date.now();try{const response=await target.client.structured<{candidates:Array<{sourcePage:string;imageUrl:string;confidence:number;evidence:string}>}>({model:target.model,effort:target.effort,web:true,maxOutputTokens:2_000,input:artworkInput,schemaName:"artwork_candidates",schema:artworkSchema}),output=response.data,first=output.candidates[0],checks:Check[]=[{name:"candidate returned",passed:Boolean(first)},{name:"source page reachable",passed:Boolean(first)&&await reachable(first.sourcePage)},{name:"direct image reachable",passed:Boolean(first)&&await reachable(first.imageUrl,true)},{name:"high stated confidence",passed:Boolean(first)&&first.confidence>=.8},{name:"tool-grounded local URLs",passed:!response.sourceUrls||Boolean(first)&&response.sourceUrls.has(first.sourcePage)&&response.sourceUrls.has(first.imageUrl)}];runs.push({caseId:"web:artwork-discovery",target:target.id,model:target.model,durationMs:Date.now()-started,usage:response.usage,valid:Boolean(first),score:weightedScore(checks),checks,output,sourceUrls:response.sourceUrls?[...response.sourceUrls]:undefined})}catch(error){runs.push({caseId:"web:artwork-discovery",target:target.id,model:target.model,durationMs:Date.now()-started,valid:false,score:0,checks:[],error:String(error)})}}
  const summary=targets.map((target)=>{const own=runs.filter((run)=>run.target===target.id),valid=own.filter((run)=>run.valid);return{target:target.id,model:target.model,cases:own.length,valid:valid.length,meanScore:Math.round(own.reduce((sum,run)=>sum+run.score,0)/Math.max(1,own.length)*100)/100,totalDurationMs:own.reduce((sum,run)=>sum+run.durationMs,0),totalTokens:own.reduce((sum,run)=>sum+(run.usage?.total_tokens??0),0)}}),report={generatedAt:new Date().toISOString(),rubric:"Fixed schema, taxonomy, semantic-anchor, safety, date, and URL reachability checks. Scores are diagnostic rather than claims of universal model quality.",targets:summary,runs};
  const directory=process.env.AI_EVAL_OUTPUT??"/tmp/curator-ai-eval";await mkdir(directory,{recursive:true});await writeFile(`${directory}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({report:`${directory}/report.json`,summary},null,2));
}
void main();
