import { cachedJson,fetchJson } from "./cache";
import { normalized } from "@/features/scanner/normalize";
type Credit={artist:{id:string;name:string};name?:string};
type Tag={name:string;count?:number};
export type MbCandidate={id:string;title:string;"first-release-date"?:string;"primary-type"?:string;"secondary-types"?:string[];"artist-credit"?:Credit[];score?:number;genres?:Tag[];tags?:Tag[]};
type SearchResult={"release-groups":MbCandidate[]};
let nextRequest=0,cooldownUntil=0;
async function limited<T>(load:()=>Promise<T>):Promise<T>{if(cooldownUntil>Date.now()){const error=new Error(`503 MusicBrainz cooldown active until ${new Date(cooldownUntil).toISOString()}`) as Error&{status:number};error.status=503;throw error}const wait=Math.max(0,nextRequest-Date.now());if(wait)await new Promise(resolve=>setTimeout(resolve,wait));nextRequest=Date.now()+1100;try{return await load()}catch(error){const status=Number((error as{status?:number}).status??0);if(status===429||status===503)cooldownUntil=Date.now()+5*60_000;throw error}}
const headers={"User-Agent":"MusicCurator/2.0 (self-hosted; contact=local-admin)",Accept:"application/json"};
async function details(candidate:MbCandidate,entityKey:string):Promise<MbCandidate>{const value=await cachedJson("musicbrainz",`release-group-details:${candidate.id}`,entityKey,90,()=>limited(()=>fetchJson<MbCandidate>(`https://musicbrainz.org/ws/2/release-group/${candidate.id}?inc=genres+tags+artist-credits&fmt=json`,{headers}))).catch(()=>candidate);return{...candidate,...value,score:candidate.score??value.score}}
export async function searchReleaseGroups(artist:string,album:string,entityKey:string):Promise<SearchResult>{const query=`artist:${JSON.stringify(artist)} AND releasegroup:${JSON.stringify(album)}`,id=`release-group-search:v2:${normalized(artist)}|${normalized(album)}`;const found=await cachedJson("musicbrainz",id,entityKey,30,()=>limited(()=>fetchJson<SearchResult>(`https://musicbrainz.org/ws/2/release-group/?query=${encodeURIComponent(query)}&limit=8&fmt=json`,{headers})));const enriched:MbCandidate[]=[];for(const candidate of found["release-groups"].slice(0,5))enriched.push(await details(candidate,entityKey));return{"release-groups":enriched}}
export async function searchReleaseGroupsByAlbum(album:string,entityKey:string):Promise<SearchResult>{const query=`releasegroup:${JSON.stringify(album)}`,id=`release-group-loose:v2:${normalized(album)}`;const found=await cachedJson("musicbrainz",id,entityKey,30,()=>limited(()=>fetchJson<SearchResult>(`https://musicbrainz.org/ws/2/release-group/?query=${encodeURIComponent(query)}&limit=12&fmt=json`,{headers})));const enriched:MbCandidate[]=[];for(const candidate of found["release-groups"].slice(0,8))enriched.push(await details(candidate,entityKey));return{"release-groups":enriched}}
const editionMarker=/\b(?:advance|anniversary|bonus|box\s*set|deluxe|edition|expanded|hi[- ]?res|japan|legacy|mfsl|pbthal|reissue|re-issue|remaster(?:ed|is(?:e|é)e?)?|remix|rip|rsd|sacd|special|super\s+deluxe|ultradisc|uhr|vinyl)\b|\b(?:16|24)[- /]?(?:bit|44|48|88|96|192)\b/i;
function removableEdition(value:string):boolean{const text=value.trim();return editionMarker.test(text)||/^\d{4}$/.test(text)||/^(?:(?:cd|disc|disk)\s*\d+|\d+\s*cd)$/i.test(text)||/^[A-Z]{2,10}[- ]?\d{3,}$/i.test(text)}
export function cleanCatalogText(value:string):string{
  let removed=false;
  let clean=value.normalize("NFKC").replace(/#{2,}/g," ").replace(/[\u2018\u2019]/g,"'").replace(/(?<=\p{L})\.(?=\p{L})/gu," ");
  clean=clean.replace(/[\[(]([^\])]+)[\])]/g,(match,inside:string)=>{if(!removableEdition(inside)&&!/^\s*\d+\s*$/.test(inside))return match;removed=true;return" "});
  clean=clean.replace(/\s*[-–—,:;]?\s*(?:disc|disk|cd)\s*0*\d+\s*$/i,"").replace(/\s*[-–—]\s*(?:new\s+)?(?:stereo\s+)?mix(?:es)?(?:\s+remaster(?:ed)?)?\s*$/i,"").replace(/\s+FLAC\s*$/i,"");
  if(removed)clean=clean.replace(/\s+\d+\s*$/,"");
  return clean.replace(/\.{2,}/g," ").replace(/\s+/g," ").trim();
}
export function cleanArtistName(value:string):string{const clean=cleanCatalogText(value),parts=clean.split(",").map(part=>part.trim()).filter(Boolean);if(parts.length!==2)return clean;if(/^the$/i.test(parts[1]))return `The ${parts[0]}`;if(!parts[0].includes(" ")&&!/[&+;/]/.test(parts[1])&&parts[1].split(/\s+/).length<=3)return `${parts[1]} ${parts[0]}`;return clean}
export async function searchReleaseGroupCandidates(artist:string,album:string,entityKey:string):Promise<SearchResult>{const cleanArtist=cleanArtistName(artist),cleanAlbum=cleanCatalogText(album),exact=await searchReleaseGroups(cleanArtist,cleanAlbum,entityKey);return exact["release-groups"].length?exact:searchReleaseGroupsByAlbum(cleanAlbum,entityKey)}
export async function artistWikidataId(artistId:string,entityKey:string):Promise<string|undefined>{type Artist={relations?:Array<{type:string;url?:{resource:string}}>};const value=await cachedJson("musicbrainz",`artist-links:${artistId}`,entityKey,90,()=>limited(()=>fetchJson<Artist>(`https://musicbrainz.org/ws/2/artist/${artistId}?inc=url-rels&fmt=json`,{headers})));return value.relations?.find(relation=>relation.type==="wikidata")?.url?.resource.split("/").pop()}
export async function resolveExactArtistId(name:string,entityKey:string):Promise<string|undefined>{type ArtistResult={artists:Array<{id:string;name:string;score:number}>};const query=`artist:${JSON.stringify(name)}`,value=await cachedJson("musicbrainz",`artist-search:${query}`,entityKey,90,()=>limited(()=>fetchJson<ArtistResult>(`https://musicbrainz.org/ws/2/artist/?query=${encodeURIComponent(query)}&limit=5&fmt=json`,{headers})));const exact=value.artists.filter(artist=>normalized(artist.name)===normalized(name)).sort((a,b)=>b.score-a.score);if(!exact[0]||exact[0].score<90)return undefined;if(exact[1]&&exact[0].score-exact[1].score<10)return undefined;return exact[0].id}
