import { cachedJson,fetchJson } from "./cache";
import { normalized } from "@/features/scanner/normalize";
type Credit={artist:{id:string;name:string};name?:string;joinphrase?:string};
type Tag={name:string;count?:number};
export type MbCandidate={id:string;title:string;disambiguation?:string;"first-release-date"?:string;"primary-type"?:string;"secondary-types"?:string[];"artist-credit"?:Credit[];score?:number;genres?:Tag[];tags?:Tag[]};
type SearchResult={"release-groups":MbCandidate[]};
let nextRequest=0,cooldownUntil=0;
export function musicBrainzCooldownRemaining():number{return Math.max(0,cooldownUntil-Date.now())}
async function limited<T>(load:()=>Promise<T>):Promise<T>{if(cooldownUntil>Date.now()){const error=new Error(`503 MusicBrainz cooldown active until ${new Date(cooldownUntil).toISOString()}`) as Error&{status:number};error.status=503;throw error}const wait=Math.max(0,nextRequest-Date.now());if(wait)await new Promise(resolve=>setTimeout(resolve,wait));nextRequest=Date.now()+1100;try{return await load()}catch(error){const status=Number((error as{status?:number}).status??0);if(status===429||status===503)cooldownUntil=Date.now()+5*60_000;throw error}}
const headers={"User-Agent":"MusicCurator/2.0 (self-hosted; contact=local-admin)",Accept:"application/json"};
async function details(candidate:MbCandidate,entityKey:string):Promise<MbCandidate>{const value=await cachedJson("musicbrainz",`release-group-details:${candidate.id}`,entityKey,90,()=>limited(()=>fetchJson<MbCandidate>(`https://musicbrainz.org/ws/2/release-group/${candidate.id}?inc=genres+tags+artist-credits&fmt=json`,{headers}))).catch(()=>candidate);return{...candidate,...value,score:candidate.score??value.score}}
const searchTtlDays=1/24;
export async function searchReleaseGroups(artist:string,album:string,entityKey:string):Promise<SearchResult>{const query=`artist:${JSON.stringify(artist)} AND releasegroup:${JSON.stringify(album)}`,id=`release-group-search:v3:${normalized(artist)}|${normalized(album)}`;const found=await cachedJson("musicbrainz",id,entityKey,searchTtlDays,()=>limited(()=>fetchJson<SearchResult>(`https://musicbrainz.org/ws/2/release-group/?query=${encodeURIComponent(query)}&limit=8&fmt=json`,{headers})));const enriched:MbCandidate[]=[];for(const candidate of found["release-groups"].slice(0,5))enriched.push(await details(candidate,entityKey));return{"release-groups":enriched}}
export async function searchReleaseGroupsByAlbum(album:string,entityKey:string):Promise<SearchResult>{const query=`releasegroup:${JSON.stringify(album)}`,id=`release-group-loose:v3:${normalized(album)}`;const found=await cachedJson("musicbrainz",id,entityKey,searchTtlDays,()=>limited(()=>fetchJson<SearchResult>(`https://musicbrainz.org/ws/2/release-group/?query=${encodeURIComponent(query)}&limit=12&fmt=json`,{headers})));const enriched:MbCandidate[]=[];for(const candidate of found["release-groups"].slice(0,8))enriched.push(await details(candidate,entityKey));return{"release-groups":enriched}}
function withoutArticle(value:string):string{return normalized(value).replace(/^(?:a|an|the)\s+/,"")}
function similarity(a:string,b:string):number{const compare=(leftValue:string,rightValue:string)=>{const left=new Set(normalized(leftValue).split(" ").filter(Boolean)),right=new Set(normalized(rightValue).split(" ").filter(Boolean));if(!left.size||!right.size)return 0;return[...left].filter(word=>right.has(word)).length/new Set([...left,...right]).size};return Math.max(compare(a,b),compare(withoutArticle(a),withoutArticle(b)))}
export function candidateCatalogTitles(candidate:MbCandidate):string[]{return[candidate.title,...(candidate.disambiguation?[`${candidate.title} (${candidate.disambiguation})`]:[])]}
export function catalogTitleSimilarity(album:string,candidate:MbCandidate):number{return Math.max(...candidateCatalogTitles(candidate).map(title=>similarity(cleanCatalogText(album),cleanCatalogText(title))))}
export function hasPlausibleCatalogMatch(album:string,candidates:MbCandidate[]):boolean{return candidates.some(candidate=>catalogTitleSimilarity(album,candidate)>=.8)}
function mergeResults(...results:SearchResult[]):SearchResult{const groups=new Map<string,MbCandidate>();for(const result of results)for(const candidate of result["release-groups"]){const previous=groups.get(candidate.id);if(!previous||Number(candidate.score??0)>Number(previous.score??0))groups.set(candidate.id,candidate)}return{"release-groups":[...groups.values()]}}
export function baseCatalogTitle(value:string):string{return cleanCatalogText(value).replace(/\s*[\[(][^\])]+[\])]\s*$/,"").trim()}
async function searchReleaseGroupVariants(artist:string,baseAlbum:string,localAlbum:string,entityKey:string):Promise<SearchResult>{const query=`artist:${JSON.stringify(artist)} AND releasegroup:${JSON.stringify(baseAlbum)}`,id=`release-group-variant:v4:${normalized(artist)}|${normalized(baseAlbum)}`;const found=await cachedJson("musicbrainz",id,entityKey,searchTtlDays,()=>limited(()=>fetchJson<SearchResult>(`https://musicbrainz.org/ws/2/release-group/?query=${encodeURIComponent(query)}&limit=25&fmt=json`,{headers}))),ranked=[...found["release-groups"]].sort((a,b)=>Math.max(...candidateCatalogTitles(b).map(title=>similarity(localAlbum,title)))-Math.max(...candidateCatalogTitles(a).map(title=>similarity(localAlbum,title))));const enriched:MbCandidate[]=[];for(const candidate of ranked.slice(0,5))enriched.push(await details(candidate,entityKey));return{"release-groups":enriched}}
const editionMarker=/\b(?:advance|anniversary|bonus|box\s*set|blu[- ]?ray|cds?|deluxe|edition|expanded|hi[- ]?res|japan|legacy|maxi[- ]?single|mfsl|mix|pbthal|promo|reissue|re-issue|remaster(?:ed|is(?:e|é)e?)?|remix|rip|rsd|sacd|single|special|super\s+deluxe|surround|ultradisc|uhr|vinyl)\b|\b(?:16|24)[- /]?(?:bit|44|48|88|96|192)\b/i;
function removableEdition(value:string):boolean{const text=value.trim();return editionMarker.test(text)||/^(?:eu|europe|japan|uk|us|usa)$/i.test(text)||/^\d{4}$/.test(text)||/^(?:(?:cd|disc|disk)\s*\d+|\d+\s*cd)$/i.test(text)||/^[A-Z][A-Z& ]{1,10}[- ]?\d{3,}$/i.test(text)}
export function cleanCatalogText(value:string):string{
  let removed=false;
  let clean=value.normalize("NFKC").replace(/#{2,}/g," ").replace(/[\u2018\u2019]/g,"'").replace(/(?<=\p{L})\.(?=\p{L})/gu," ");
  clean=clean.replace(/[\[(]([^\])]+)[\])]/g,(match,inside:string)=>{if(!removableEdition(inside)&&!/^\s*\d+\s*$/.test(inside))return match;removed=true;return" "});
  clean=clean.replace(/\s*[-–—,:;]?\s*(?:disc|disk|cd)(?:\s*0*\d+)?\s*$/i,"").replace(/\s*[-–—]\s*(?:new\s+)?(?:stereo\s+)?mix(?:es)?(?:\s+remaster(?:ed)?)?\s*$/i,"").replace(/\s*[-–—]\s*(?:maxi[- ]?)?(?:single|ep)\s*$/i,"").replace(/\s+FLAC\s*$/i,"");
  if(removed)clean=clean.replace(/\s+\d+\s*$/,"");
  return clean.replace(/\.{2,}/g," ").replace(/\s+/g," ").trim();
}
export function cleanArtistName(value:string):string{const clean=cleanCatalogText(value).replace(/^the(?=[A-Z])/i,"The "),parts=clean.split(",").map(part=>part.trim()).filter(Boolean);if(parts.length!==2)return clean;if(/^the$/i.test(parts[1]))return `The ${parts[0]}`;if(!parts[0].includes(" ")&&!/[&+;/]/.test(parts[1])&&parts[1].split(/\s+/).length<=3)return `${parts[1]} ${parts[0]}`;return clean}
export function catalogTitleVariants(artist:string,album:string):string[]{const cleanArtist=cleanArtistName(artist),cleanAlbum=cleanCatalogText(album),values=new Set<string>(),add=(value:string)=>{const clean=value.replace(/^[\s\p{P}\p{S}]+/u,"").replace(/[\s\p{P}\p{S}]+$/u,"").replace(/\s+/g," ").trim();if(clean)values.add(clean)};add(cleanAlbum);let base=cleanAlbum;for(let index=0;index<3;index+=1){const next=baseCatalogTitle(base);if(!next||next===base)break;add(next);base=next}if(normalized(cleanAlbum).startsWith(`${normalized(cleanArtist)} `)){const remainder=cleanAlbum.slice(cleanArtist.length);add(remainder);add(baseCatalogTitle(remainder))}for(const value of [...values]){if(/^(?:a|an|the)\s+/i.test(value))add(value.replace(/^(?:a|an|the)\s+/i,""));if(value.split(/\s+/).length>=3&&/\s+\d{2}$/.test(value))add(value.replace(/\s+\d{2}$/,"").trim())}return[...values]}
export async function searchReleaseGroupCandidates(artist:string,album:string,entityKey:string):Promise<SearchResult>{const cleanArtist=cleanArtistName(artist),variants=catalogTitleVariants(cleanArtist,album),cleanAlbum=variants[0]??cleanCatalogText(album),exact=await searchReleaseGroups(cleanArtist,cleanAlbum,entityKey);if(hasPlausibleCatalogMatch(cleanAlbum,exact["release-groups"]))return exact;const collected=[exact];for(const variant of variants.slice(1)){const found=await searchReleaseGroupVariants(cleanArtist,variant,variant,entityKey);collected.push(found);if(hasPlausibleCatalogMatch(variant,found["release-groups"]))return mergeResults(...collected)}const looseTitle=variants.at(-1)??cleanAlbum,loose=await searchReleaseGroupsByAlbum(looseTitle,entityKey).catch(()=>({"release-groups":[]}));return mergeResults(...collected,loose)}
export async function artistWikidataId(artistId:string,entityKey:string):Promise<string|undefined>{type Artist={relations?:Array<{type:string;url?:{resource:string}}>};const value=await cachedJson("musicbrainz",`artist-links:${artistId}`,entityKey,90,()=>limited(()=>fetchJson<Artist>(`https://musicbrainz.org/ws/2/artist/${artistId}?inc=url-rels&fmt=json`,{headers})));return value.relations?.find(relation=>relation.type==="wikidata")?.url?.resource.split("/").pop()}
export async function resolveExactArtistId(name:string,entityKey:string):Promise<string|undefined>{type ArtistResult={artists:Array<{id:string;name:string;score:number}>};const query=`artist:${JSON.stringify(name)}`,value=await cachedJson("musicbrainz",`artist-search:${query}`,entityKey,90,()=>limited(()=>fetchJson<ArtistResult>(`https://musicbrainz.org/ws/2/artist/?query=${encodeURIComponent(query)}&limit=5&fmt=json`,{headers})));const exact=value.artists.filter(artist=>normalized(artist.name)===normalized(name)).sort((a,b)=>b.score-a.score);if(!exact[0]||exact[0].score<90)return undefined;if(exact[1]&&exact[0].score-exact[1].score<10)return undefined;return exact[0].id}
