import { config } from "@/config";
let session:{cookie:string;expires:number}|undefined;
async function cookie(){if(session&&session.expires>Date.now())return session.cookie;const response=await fetch(`${config.QBITTORRENT_URL}/api/v2/auth/login`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Origin:config.QBITTORRENT_URL,Referer:`${config.QBITTORRENT_URL}/`},body:new URLSearchParams({username:config.QBITTORRENT_USERNAME,password:config.QBITTORRENT_PASSWORD}),signal:AbortSignal.timeout(5_000)}),text=await response.text();if(!response.ok||/^fails/i.test(text.trim())||!response.headers.get("set-cookie"))throw new Error("qBittorrent authentication failed");session={cookie:response.headers.get("set-cookie")?.split(";")[0]??"",expires:Date.now()+20*60_000};return session.cookie}
async function call(path:string,values?:Record<string,string>){const response=await fetch(`${config.QBITTORRENT_URL}/api/v2${path}`,{method:values?"POST":"GET",headers:{Cookie:await cookie(),...(values?{"Content-Type":"application/x-www-form-urlencoded"}:{})},body:values?new URLSearchParams(values):undefined,signal:AbortSignal.timeout(30_000)});if(!response.ok)throw new Error(`qBittorrent ${path} failed (${response.status})`);const text=await response.text();return text?JSON.parse(text):undefined}
export type Torrent={hash:string;name:string;state:string;category:string;downloaded:number;amount_left:number;progress:number;dlspeed:number;num_seeds:number;num_complete:number;availability:number;added_on:number;ratio:number;tracker:string;completion_on:number;size:number};
export const qbitTorrents=()=>call(`/torrents/info?category=${encodeURIComponent(config.QBITTORRENT_CATEGORY)}`) as Promise<Torrent[]>;
export const qbitTransfer=()=>call("/transfer/info") as Promise<{dl_info_speed:number;dl_info_data:number;connection_status:string}>;
export const qbitPreferences=()=>call("/app/preferences") as Promise<Record<string,unknown>>;
export const setPreferences=(values:Record<string,unknown>)=>call("/app/setPreferences",{json:JSON.stringify(values)});
export const reannounce=(hash:string)=>call("/torrents/reannounce",{hashes:hash});
export const topPriority=(hashes:string[])=>hashes.length?call("/torrents/topPrio",{hashes:hashes.join("|")}):Promise.resolve();
export const forceStart=(hash:string,value:boolean)=>call("/torrents/setForceStart",{hashes:hash,value:String(value)});
export const stopTorrent=(hash:string)=>call("/torrents/stop",{hashes:hash});
export const removeTorrent=(hash:string,files:boolean)=>call("/torrents/delete",{hashes:hash,deleteFiles:String(files)});
async function ubuntuTorrentUrl(){const response=await fetch("https://releases.ubuntu.com/24.04/",{signal:AbortSignal.timeout(10_000)});if(!response.ok)throw new Error("Ubuntu probe source unavailable");const html=await response.text(),match=html.match(/href="([^"]*desktop-amd64\.iso\.torrent)"/i)??html.match(/href="([^"]*live-server-amd64\.iso\.torrent)"/i);if(!match)throw new Error("Ubuntu probe torrent not found");return new URL(match[1],response.url).toString()}
export async function connectivityProbe(){const category="curator-diagnostic",stale=await call(`/torrents/info?category=${category}`) as Torrent[];if(stale.length){await removeTorrent(stale.map(item=>item.hash).join("|"),true);await new Promise(resolve=>setTimeout(resolve,1_000))}const before=new Set((await call(`/torrents/info?category=${category}`) as Torrent[]).map(item=>item.hash));let hash="";try{await call("/torrents/add",{urls:await ubuntuTorrentUrl(),category,stopped:"true"});for(let tries=0;tries<10&&!hash;tries++){await new Promise(resolve=>setTimeout(resolve,1_000));hash=((await call(`/torrents/info?category=${category}`) as Torrent[]).find(item=>!before.has(item.hash)))?.hash??""}if(!hash)throw new Error("Diagnostic torrent was not accepted");await call("/torrents/setDownloadLimit",{hashes:hash,limit:String(1024*1024)});await topPriority([hash]);await forceStart(hash,true);const started=Date.now();let downloaded=0,seeds=0,state="unknown";while(Date.now()-started<60_000&&downloaded<5*1024*1024){await new Promise(resolve=>setTimeout(resolve,2_000));const item=(await call(`/torrents/info?hashes=${hash}`) as Torrent[])[0];if(!item)break;downloaded=item.downloaded;seeds=item.num_seeds;state=item.state;if(downloaded>0)break}return{ok:downloaded>0,downloaded,seeds,state}}finally{if(hash){await forceStart(hash,false).catch(()=>{});await stopTorrent(hash).catch(()=>{});await new Promise(resolve=>setTimeout(resolve,1_000));await removeTorrent(hash,true).catch(()=>{})}}}
