import { db } from "@/features/db/client";
import type { AcquisitionTarget } from "./types";
import { grabRelease,releases } from "./lidarr";
import { releaseScore,retryDelay } from "./policy";
import { sourceScores,withHybrid } from "./quality";
import { updateTarget } from "./repository";

function quality(item:Record<string,unknown>){const value=item.quality as{quality?:{name?:string}}|undefined;return String(value?.quality?.name??item.quality??"")}
function viable(item:Record<string,unknown>,fallback:boolean){const name=quality(item),lossless=/flac|alac|ape|wavpack/i.test(name),mp3=/mp3.*(v0|320)/i.test(name);return(lossless||(fallback&&mp3))&&String(item.protocol??"torrent")==="torrent"&&Number(item.seeders??0)>0&&!Boolean(item.rejected)&&!(item.rejections as unknown[]|undefined)?.length}
export function confirmedGrabConflict(error:unknown){const message=String(error);return/Lidarr \/release failed \(409\)/.test(message)||(/Lidarr \/release failed \(500\)/.test(message)&&/409:Conflict/.test(message)&&/qbittorrent|torrents\/add/i.test(message))}
function failedReleaseGuids(target:AcquisitionTarget):string[]{try{const value=JSON.parse(target.detail_json??"{}") as{failedReleaseGuids?:unknown};return Array.isArray(value.failedReleaseGuids)?value.failedReleaseGuids.map(String).filter(Boolean).slice(-24):[]}catch{return[]}}
async function candidates(target:AcquisitionTarget,fallback:boolean,excluded:Set<string>){const scores=sourceScores();return(await releases(target.lidarr_album_id)).filter(item=>{const guid=String(item.guid??"");return viable(item,fallback)&&guid!==target.last_release_guid&&!excluded.has(guid)}).map(item=>{const source=String(item.indexer??item.indexerName??"unknown"),sourceScore=scores.find(value=>value.name===source.replace(/ \(Prowlarr\)$/i,""))?.score??.5;return{item,score:releaseScore({seeders:Number(item.seeders??0),size:Number(item.size??0),trackCount:Number(item.trackCount??10),quality:quality(item),sourceScore,importRate:sourceScore}),source}}).sort((a,b)=>b.score-a.score)}
export async function findRelease(target:AcquisitionTarget,fallback:boolean){const work=async()=>{const failedGuids=new Set(failedReleaseGuids(target)),list=await candidates(target,fallback,failedGuids),day=new Date().toISOString().slice(0,10),attempts=target.attempts_day===day?target.attempts_today+1:1,retryAttempts=fallback?Math.max(3,attempts):attempts,next=new Date(Date.now()+retryDelay(retryAttempts)*3_600_000).toISOString();let best: (typeof list)[number] | undefined,grabAttempts=0;const failedSources = new Set<string>();for(const candidate of list){if(grabAttempts>=3)break;grabAttempts++;try{await grabRelease(candidate.item);best=candidate;break}catch(error){if(!confirmedGrabConflict(error))throw error;const guid=String(candidate.item.guid??"");failedSources.add(candidate.source);if(guid)failedGuids.add(guid);db().prepare("INSERT INTO source_outcomes(indexer_name,event,detail_json) VALUES(?,'grab_failure',?)").run(candidate.source,JSON.stringify({albumId:target.lidarr_album_id,guid}))}}if(!best){updateTarget(target.id,{status:"staged",attempts_today:attempts,attempts_day:day,last_search_at:new Date().toISOString(),next_retry_at:next,quality_phase:fallback?"hybrid":"lossless",detail_json:JSON.stringify({reason:list.length?"Release downloads failed":"No viable release",failedSources:[...failedSources],failedReleaseGuids:[...failedGuids].slice(-24)})});return{grabbed:false,reason:"No viable release; retry scheduled"}}const guid=String(best.item.guid??"");updateTarget(target.id,{status:"queued",source_name:best.source,last_release_guid:guid,attempts_today:attempts,attempts_day:day,last_search_at:new Date().toISOString(),next_retry_at:next,quality_phase:fallback?"hybrid":"lossless",detail_json:"{}"});db().prepare("INSERT INTO source_outcomes(indexer_name,event,detail_json) VALUES(?,'grab',?)").run(best.source,JSON.stringify({albumId:target.lidarr_album_id,guid,score:best.score}));return{grabbed:true,source:best.source,guid,score:best.score}};return fallback&&target.lidarr_artist_id?withHybrid(target.lidarr_artist_id,work):work()}
