import { db } from "@/features/db/client";
import type { AcquisitionTarget } from "./types";
import { grabRelease,releases } from "./lidarr";
import { releaseScore,retryDelay } from "./policy";
import { sourceScores,withHybrid } from "./quality";
import { updateTarget } from "./repository";

function quality(item:Record<string,unknown>){const value=item.quality as{quality?:{name?:string}}|undefined;return String(value?.quality?.name??item.quality??"")}
function viable(item:Record<string,unknown>,fallback:boolean){const name=quality(item),lossless=/flac|alac|ape|wavpack/i.test(name),mp3=/mp3.*(v0|320)/i.test(name);return(lossless||(fallback&&mp3))&&String(item.protocol??"torrent")==="torrent"&&Number(item.seeders??0)>0&&!Boolean(item.rejected)&&!(item.rejections as unknown[]|undefined)?.length}
async function candidates(target:AcquisitionTarget,fallback:boolean){const scores=sourceScores();return(await releases(target.lidarr_album_id)).filter(item=>viable(item,fallback)&&String(item.guid??"")!==target.last_release_guid).map(item=>{const source=String(item.indexer??item.indexerName??"unknown"),sourceScore=scores.find(value=>value.name===source.replace(/ \(Prowlarr\)$/i,""))?.score??.5;return{item,score:releaseScore({seeders:Number(item.seeders??0),size:Number(item.size??0),trackCount:Number(item.trackCount??10),quality:quality(item),sourceScore,importRate:.5}),source}}).sort((a,b)=>b.score-a.score)}
export async function findRelease(target:AcquisitionTarget,fallback:boolean){const work=async()=>{const list=await candidates(target,fallback),day=new Date().toISOString().slice(0,10),attempts=target.attempts_day===day?target.attempts_today+1:1,next=new Date(Date.now()+retryDelay(attempts)*3_600_000).toISOString();let best: (typeof list)[number] | undefined;const failedSources = new Set<string>();for(const candidate of list){if(failedSources.has(candidate.source))continue;if(failedSources.size>=3)break;try{await grabRelease(candidate.item);best=candidate;break}catch(error){if(!String(error).startsWith("Error: Lidarr /release failed (409)"))throw error;failedSources.add(candidate.source);db().prepare("INSERT INTO source_outcomes(indexer_name,event,detail_json) VALUES(?,'grab_failure',?)").run(candidate.source,JSON.stringify({albumId:target.lidarr_album_id,guid:String(candidate.item.guid??"")}))}}if(!best){updateTarget(target.id,{status:"staged",attempts_today:attempts,attempts_day:day,last_search_at:new Date().toISOString(),next_retry_at:next,quality_phase:fallback?"hybrid":"lossless",detail_json:JSON.stringify({reason:list.length?"Release downloads failed":"No viable release",failedSources:[...failedSources]})});return{grabbed:false,reason:"No viable release; retry scheduled"}}const guid=String(best.item.guid??"");updateTarget(target.id,{status:"queued",source_name:best.source,last_release_guid:guid,attempts_today:attempts,attempts_day:day,last_search_at:new Date().toISOString(),next_retry_at:next,quality_phase:fallback?"hybrid":"lossless"});db().prepare("INSERT INTO source_outcomes(indexer_name,event,detail_json) VALUES(?,'grab',?)").run(best.source,JSON.stringify({albumId:target.lidarr_album_id,guid,score:best.score}));return{grabbed:true,source:best.source,guid,score:best.score}};return fallback&&target.lidarr_artist_id?withHybrid(target.lidarr_artist_id,work):work()}
