import { config } from "@/config";
let cache:{expires:number;value:unknown}|undefined;
async function json(url:string,init:RequestInit={}):Promise<unknown>{const response=await fetch(url,{...init,signal:AbortSignal.timeout(2_000)});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return response.json()}
async function settled(name:string,work:()=>Promise<unknown>):Promise<[string,unknown]>{try{return[name,{ok:true,data:await work()}]}catch(error){return[name,{ok:false,error:String(error)}]}}
async function lidarr():Promise<unknown>{const headers={"X-Api-Key":config.LIDARR_API_KEY};const [health,queue]=await Promise.all([json(`${config.LIDARR_URL}/api/v1/health`,{headers}),json(`${config.LIDARR_URL}/api/v1/queue?page=1&pageSize=1`,{headers})]);return{health,queue:Number((queue as{totalRecords?:number}).totalRecords??0)}}
async function prowlarr():Promise<unknown>{const headers={"X-Api-Key":config.PROWLARR_API_KEY};const [health,indexers]=await Promise.all([json(`${config.PROWLARR_URL}/api/v1/health`,{headers}),json(`${config.PROWLARR_URL}/api/v1/indexer`,{headers})]);const list=indexers as Array<{name:string;enable:boolean}>;return{health,enabled:list.filter(item=>item.enable).length,total:list.length,names:list.filter(item=>item.enable).map(item=>item.name)}}
async function qbittorrent():Promise<unknown>{const login=await fetch(`${config.QBITTORRENT_URL}/api/v2/auth/login`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Origin:config.QBITTORRENT_URL,Referer:`${config.QBITTORRENT_URL}/`},body:new URLSearchParams({username:config.QBITTORRENT_USERNAME,password:config.QBITTORRENT_PASSWORD}),signal:AbortSignal.timeout(2_000)}),loginText=await login.text(),cookie=login.headers.get("set-cookie")?.split(";")[0]??"";if(!login.ok||/^fails/i.test(loginText.trim())||!cookie)throw new Error(`Credentials rejected (${login.status})`);const headers={Cookie:cookie};const [itemsRaw,transferRaw,syncRaw]=await Promise.all([json(`${config.QBITTORRENT_URL}/api/v2/torrents/info?category=${encodeURIComponent(config.QBITTORRENT_CATEGORY)}`,{headers}),json(`${config.QBITTORRENT_URL}/api/v2/transfer/info`,{headers}),json(`${config.QBITTORRENT_URL}/api/v2/sync/maindata?rid=0`,{headers})]),items=itemsRaw as Array<{state:string;progress:number;dlspeed:number;amount_left:number;num_seeds:number;num_leechs:number}>,transfer=transferRaw as Record<string,unknown>,server=(syncRaw as{server_state?:Record<string,unknown>}).server_state??{},states:Record<string,number>={};for(const item of items)states[item.state]=(states[item.state]??0)+1;const count=(names:string[])=>items.filter(item=>names.includes(item.state)).length;return{torrents:items.length,states,downloadSpeed:Number(transfer.dl_info_speed??0),uploadSpeed:Number(transfer.up_info_speed??0),sessionDownloaded:Number(transfer.dl_info_data??0),sessionUploaded:Number(transfer.up_info_data??0),connection:String(transfer.connection_status??"unknown"),active:items.filter(item=>item.dlspeed>0).length,downloading:count(["downloading","forcedDL","metaDL","checkingDL"]),queued:count(["queuedDL"]),stalled:count(["stalledDL","metaDL"]),paused:count(["pausedDL","stoppedDL"]),seeding:count(["uploading","forcedUP","stalledUP","queuedUP"]),completed:items.filter(item=>item.progress>=1).length,remainingBytes:items.reduce((sum,item)=>sum+Number(item.amount_left??0),0),connectedSeeds:items.reduce((sum,item)=>sum+Number(item.num_seeds??0),0),connectedPeers:items.reduce((sum,item)=>sum+Number(item.num_leechs??0),0),freeSpace:Number(server.free_space_on_disk??0),dhtNodes:Number(server.dht_nodes??0)}}
async function navidrome():Promise<unknown>{const response=await fetch(config.NAVIDROME_URL,{signal:AbortSignal.timeout(2_000)});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return{reachable:true}}
export async function stackSummary(force=false):Promise<unknown>{if(!force&&cache&&cache.expires>Date.now())return cache.value;const entries=await Promise.all([settled("lidarr",lidarr),settled("prowlarr",prowlarr),settled("qbittorrent",qbittorrent),settled("navidrome",navidrome)]);const value=Object.fromEntries(entries);cache={expires:Date.now()+15_000,value};return value}
