import { config } from "@/config";
let cache:{expires:number;value:unknown}|undefined;
async function json(url:string,init:RequestInit={}):Promise<unknown>{const response=await fetch(url,{...init,signal:AbortSignal.timeout(2_000)});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return response.json()}
async function settled(name:string,work:()=>Promise<unknown>):Promise<[string,unknown]>{try{return[name,{ok:true,data:await work()}]}catch(error){return[name,{ok:false,error:String(error)}]}}
async function lidarr():Promise<unknown>{const headers={"X-Api-Key":config.LIDARR_API_KEY};const [health,queue]=await Promise.all([json(`${config.LIDARR_URL}/api/v1/health`,{headers}),json(`${config.LIDARR_URL}/api/v1/queue?page=1&pageSize=1`,{headers})]);return{health,queue:Number((queue as{totalRecords?:number}).totalRecords??0)}}
async function prowlarr():Promise<unknown>{const headers={"X-Api-Key":config.PROWLARR_API_KEY};const [health,indexers]=await Promise.all([json(`${config.PROWLARR_URL}/api/v1/health`,{headers}),json(`${config.PROWLARR_URL}/api/v1/indexer`,{headers})]);const list=indexers as Array<{name:string;enable:boolean}>;return{health,enabled:list.filter(item=>item.enable).length,total:list.length,names:list.filter(item=>item.enable).map(item=>item.name)}}
async function qbittorrent():Promise<unknown>{const login=await fetch(`${config.QBITTORRENT_URL}/api/v2/auth/login`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Origin:config.QBITTORRENT_URL,Referer:`${config.QBITTORRENT_URL}/`},body:new URLSearchParams({username:config.QBITTORRENT_USERNAME,password:config.QBITTORRENT_PASSWORD}),signal:AbortSignal.timeout(2_000)});if(!login.ok)throw new Error(`Credentials rejected (${login.status})`);const cookie=login.headers.get("set-cookie")?.split(";")[0]??"",headers={Cookie:cookie};const [items,transfer]=await Promise.all([json(`${config.QBITTORRENT_URL}/api/v2/torrents/info?category=${encodeURIComponent(config.QBITTORRENT_CATEGORY)}`,{headers}),json(`${config.QBITTORRENT_URL}/api/v2/transfer/info`,{headers})]);const states:Record<string,number>={};for(const item of items as Array<{state:string}>)states[item.state]=(states[item.state]??0)+1;const value=transfer as Record<string,unknown>;return{torrents:(items as unknown[]).length,states,downloadSpeed:value.dl_info_speed,uploadSpeed:value.up_info_speed,connection:value.connection_status}}
async function navidrome():Promise<unknown>{const response=await fetch(config.NAVIDROME_URL,{signal:AbortSignal.timeout(2_000)});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return{reachable:true}}
export async function stackSummary(force=false):Promise<unknown>{if(!force&&cache&&cache.expires>Date.now())return cache.value;const entries=await Promise.all([settled("lidarr",lidarr),settled("prowlarr",prowlarr),settled("qbittorrent",qbittorrent),settled("navidrome",navidrome)]);const value=Object.fromEntries(entries);cache={expires:Date.now()+15_000,value};return value}
